type CatalogEntry = {
  key: string;
  label: string;
  description: string;
};

type PermissionGroupDefinition = {
  module: string;
  category: string;
  permissions: CatalogEntry[];
};

type StarterRolePreset = {
  name: string;
  label: string;
  description: string;
  permissionKeys?: readonly string[];
  grantsAllSystemPermissions?: boolean;
};

export const profileStatusCatalog = [
  { key: "applicant", label: "Applicant", description: "Prospective member awaiting intake review." },
  { key: "recruit", label: "Recruit", description: "Member in initial onboarding or probationary status." },
  { key: "active", label: "Active", description: "Fully active member in good standing." },
  { key: "reserve", label: "Reserve", description: "Member available on a reserve or reduced-participation basis." },
  { key: "loa", label: "LOA", description: "Member currently on leave of absence." },
  { key: "inactive", label: "Inactive", description: "Member not actively participating but retained in records." },
  { key: "retired", label: "Retired", description: "Former member retained for historical reporting." },
  { key: "discharged", label: "Discharged", description: "Member removed from the unit structure." },
  { key: "banned", label: "Banned", description: "Member barred from community participation." },
] as const satisfies readonly CatalogEntry[];

export const spearheadUnitCatalog = [
  { key: "spearhead-command", name: "Spearhead Command", shortName: "Spearhead", parentKey: null, sortOrder: 10 },
  { key: "reaper", name: "3rd Infantry Division", shortName: "Reaper", parentKey: "spearhead-command", sortOrder: 20 },
  { key: "misfit", name: "75th Ranger Regiment", shortName: "Misfit", parentKey: "spearhead-command", sortOrder: 30 },
  { key: "gambler", name: "1st Air Cavalry Brigade", shortName: "Gambler", parentKey: "spearhead-command", sortOrder: 40 },
  { key: "viking", name: "Detachment-7", shortName: "Viking", parentKey: "spearhead-command", sortOrder: 50 },
] as const;

export const qualificationCategoryCatalog = [
  { key: "basic-infantry", label: "Basic Infantry", description: "Entry-level infantry readiness qualifications.", sortOrder: 10 },
  { key: "leadership", label: "Leadership", description: "Leadership-focused development and command qualifications.", sortOrder: 20 },
  { key: "medical", label: "Medical", description: "Medical treatment, triage, and combat lifesaver training.", sortOrder: 30 },
  { key: "communications", label: "Communications", description: "Radio procedure, signal, and comms workflow training.", sortOrder: 40 },
  { key: "aviation", label: "Aviation", description: "Flight, aircrew, and air support-related qualifications.", sortOrder: 50 },
  { key: "reconnaissance", label: "Reconnaissance", description: "Recon, surveillance, and scouting qualifications.", sortOrder: 60 },
  { key: "mission-maker", label: "Operation Planner", description: "Operation creation, scenario support, and operations prep qualifications.", sortOrder: 70 },
  { key: "zeus", label: "Zeus", description: "Game master and operational oversight qualifications.", sortOrder: 80 },
  { key: "staff", label: "Staff", description: "Staff workflow and command-support qualifications.", sortOrder: 90 },
  { key: "unit-specific", label: "Unit-Specific", description: "Qualifications defined by a specific unit or detachment.", sortOrder: 100 },
] as const;

export const documentCategoryCatalog = [
  { key: "general", label: "General", description: "General knowledge-base content and reference material.", sortOrder: 10 },
  { key: "sop", label: "SOP", description: "Standard operating procedures for repeatable unit workflows.", sortOrder: 20 },
  { key: "tacsop", label: "TACSOP", description: "Tactical SOP references for field and operation execution.", sortOrder: 30 },
  { key: "training", label: "Training", description: "Training guides, qualification prep, and instructional material.", sortOrder: 40 },
  { key: "administration", label: "Administration", description: "Administrative policy, forms, and internal guidance.", sortOrder: 50 },
  { key: "intel", label: "Intel", description: "Intelligence briefs, reference packs, and operation prep material.", sortOrder: 60 },
  { key: "operations", label: "Operations", description: "Operational planning and execution references.", sortOrder: 70 },
  { key: "conop", label: "CONOP", description: "Concept of operations and operation briefing content.", sortOrder: 80 },
  { key: "aar", label: "AAR", description: "After-action review material and historical operation documentation.", sortOrder: 90 },
  { key: "forms", label: "Forms", description: "Reusable forms, templates, and admin paperwork.", sortOrder: 100 },
  { key: "templates", label: "Templates", description: "Boilerplates for future operation, policy, and training documents.", sortOrder: 110 },
  { key: "public", label: "Public", description: "Member-facing public reference content.", sortOrder: 120 },
  { key: "restricted", label: "Restricted", description: "Restricted content that requires additional access controls.", sortOrder: 130 },
  { key: "unit-specific", label: "Unit-Specific", description: "Content owned by or scoped to a specific unit.", sortOrder: 140 },
] as const;

export const formTemplateTypeCatalog = [
  { key: "recruit_application", label: "Recruit Application", description: "Initial application intake for prospective members." },
  { key: "unit_transfer_request", label: "Unit Transfer Request", description: "Request reassignment between units or detachments." },
  { key: "loa_request", label: "LOA Request", description: "Request leave of absence or temporary inactive accommodation." },
  { key: "staff_application", label: "Staff Application", description: "Apply for a staff-facing support or command role." },
  { key: "instructor_application", label: "Instructor Application", description: "Apply for instructor or training cadre responsibilities." },
  { key: "rasp_application", label: "RASP Application", description: "Placeholder application type for future RASP workflow support." },
] as const satisfies readonly CatalogEntry[];

export const formFieldTypeCatalog = [
  { key: "short_text", label: "Short Text", description: "Single-line free-text response." },
  { key: "long_text", label: "Long Text", description: "Long-form paragraph response." },
  { key: "dropdown", label: "Dropdown", description: "Select a single option from a dropdown list." },
  { key: "checkbox", label: "Checkbox", description: "Confirm a boolean response." },
  { key: "radio", label: "Radio", description: "Choose one option from a small option set." },
  { key: "date", label: "Date", description: "Date-only field for scheduling or request timing." },
  { key: "discord_name", label: "Discord Name", description: "Portal-populated Discord display name or username reference." },
  { key: "steam_arma_id", label: "Steam / Arma ID", description: "Identifier field for Steam or Arma profile references." },
  { key: "unit_selector", label: "Unit Selector", description: "Select a target or preferred unit from known Spearhead units." },
  { key: "member_selector", label: "Member Selector", description: "Select a portal member profile for staff-facing workflows." },
  { key: "file_upload", label: "File Upload Placeholder", description: "Placeholder field reserved for future attachment support." },
  { key: "acknowledgement_checkbox", label: "Acknowledgement Checkbox", description: "Confirm acknowledgement of a policy, requirement, or statement." },
] as const satisfies readonly CatalogEntry[];

export const submissionStatusCatalog = [
  { key: "draft", label: "Draft", description: "Submission is being prepared and has not been formally routed.", sortOrder: 10, isDefault: true, isTerminal: false },
  { key: "submitted", label: "Submitted", description: "Submission was submitted and is waiting to enter review.", sortOrder: 20, isDefault: false, isTerminal: false },
  { key: "under_review", label: "Under Review", description: "Submission is actively being reviewed by assigned staff.", sortOrder: 30, isDefault: false, isTerminal: false },
  { key: "changes_requested", label: "Changes Requested", description: "Reviewer requested clarification or changes before approval.", sortOrder: 40, isDefault: false, isTerminal: false },
  { key: "approved", label: "Approved", description: "Submission was approved and is ready for downstream workflow follow-up.", sortOrder: 50, isDefault: false, isTerminal: true },
  { key: "denied", label: "Denied", description: "Submission was denied and closed.", sortOrder: 60, isDefault: false, isTerminal: true },
  { key: "withdrawn", label: "Withdrawn", description: "Submitter withdrew the request before final resolution.", sortOrder: 70, isDefault: false, isTerminal: true },
  { key: "archived", label: "Archived", description: "Submission is retained for history but removed from active queues.", sortOrder: 80, isDefault: false, isTerminal: true },
] as const;

export const rankCatalog = [
  { key: "pvt", label: "Private", abbreviation: "PVT", sortOrder: 10, isOfficer: false },
  { key: "pv2", label: "Private Second Class", abbreviation: "PV2", sortOrder: 20, isOfficer: false },
  { key: "pfc", label: "Private First Class", abbreviation: "PFC", sortOrder: 30, isOfficer: false },
  { key: "spc", label: "Specialist", abbreviation: "SPC", sortOrder: 40, isOfficer: false },
  { key: "cpl", label: "Corporal", abbreviation: "CPL", sortOrder: 50, isOfficer: false },
  { key: "sgt", label: "Sergeant", abbreviation: "SGT", sortOrder: 60, isOfficer: false },
  { key: "ssg", label: "Staff Sergeant", abbreviation: "SSG", sortOrder: 70, isOfficer: false },
  { key: "sfc", label: "Sergeant First Class", abbreviation: "SFC", sortOrder: 80, isOfficer: false },
  { key: "msg", label: "Master Sergeant", abbreviation: "MSG", sortOrder: 90, isOfficer: false },
  { key: "1sg", label: "First Sergeant", abbreviation: "1SG", sortOrder: 100, isOfficer: false },
  { key: "sgm", label: "Sergeant Major", abbreviation: "SGM", sortOrder: 110, isOfficer: false },
  { key: "csm", label: "Command Sergeant Major", abbreviation: "CSM", sortOrder: 120, isOfficer: false },
  { key: "2lt", label: "Second Lieutenant", abbreviation: "2LT", sortOrder: 130, isOfficer: true },
  { key: "1lt", label: "First Lieutenant", abbreviation: "1LT", sortOrder: 140, isOfficer: true },
  { key: "cpt", label: "Captain", abbreviation: "CPT", sortOrder: 150, isOfficer: true },
  { key: "maj", label: "Major", abbreviation: "MAJ", sortOrder: 160, isOfficer: true },
  { key: "ltc", label: "Lieutenant Colonel", abbreviation: "LTC", sortOrder: 170, isOfficer: true },
  { key: "col", label: "Colonel", abbreviation: "COL", sortOrder: 180, isOfficer: true },
] as const;

export const campaignStatusCatalog = [
  "planning",
  "preparing",
  "active",
  "completed",
  "archived",
] as const;

export const eventTypeCatalog = [
  {
    key: "operation",
    label: "Weekend Operation",
    description: "Primary weekend operation inside a deployment week.",
  },
  {
    key: "patrol",
    label: "Patrol",
    description: "Member-led patrol or weekday operation that normally requires a follow-up AAR.",
  },
  {
    key: "training",
    label: "Training",
    description: "Formal training, lane, or qualification event.",
  },
  {
    key: "meeting",
    label: "Meeting",
    description: "Leadership, staff, or unit meeting.",
  },
  {
    key: "community-event",
    label: "Community Event",
    description: "Community-wide or social event outside standard operations.",
  },
] as const satisfies readonly CatalogEntry[];

export const eventStatusCatalog = [
  {
    key: "draft",
    label: "Draft",
    description: "Created but not yet published to the portal audience.",
  },
  {
    key: "published",
    label: "Published",
    description: "Visible for RSVP and attendance planning.",
  },
  {
    key: "cancelled",
    label: "Cancelled",
    description: "Cancelled and no longer expected to occur.",
  },
  {
    key: "completed",
    label: "Completed",
    description: "Event occurred and attendance has been finalized.",
  },
  {
    key: "archived",
    label: "Archived",
    description: "Historical event retained for reporting and audit purposes.",
  },
] as const satisfies readonly CatalogEntry[];

export const patrolTypeCatalog = [
  { key: "recon", label: "Recon", description: "Reconnaissance patrol focused on intelligence gathering." },
  { key: "combat-patrol", label: "Combat Patrol", description: "Combat patrol expected to make or exploit contact." },
  { key: "logistics", label: "Logistics", description: "Logistics, resupply, or movement support patrol." },
  { key: "qrf", label: "QRF", description: "Quick reaction patrol or response posture." },
  { key: "training", label: "Training", description: "Lightweight patrol used for practice or familiarization." },
  { key: "intel", label: "Intel", description: "Patrol focused on intelligence validation or collection." },
  { key: "other", label: "Other", description: "Other lightweight patrol activity." },
] as const satisfies readonly CatalogEntry[];

export const patrolStatusCatalog = [
  { key: "planning", label: "Planning", description: "Patrol is being prepared but has not started." },
  { key: "running", label: "Running", description: "Patrol is active now." },
  { key: "completed", label: "Completed", description: "Patrol has ended and is ready for AAR follow-up." },
  { key: "awaiting-aar", label: "Awaiting AAR", description: "Patrol is complete and the required AAR has not been submitted." },
  { key: "aar-submitted", label: "AAR Submitted", description: "Patrol AAR text has been submitted." },
  { key: "reviewed", label: "Reviewed", description: "Patrol AAR has been reviewed by S3." },
  { key: "archived", label: "Archived", description: "Patrol is closed for active workflow purposes." },
] as const satisfies readonly CatalogEntry[];

export const deploymentResourceTypeCatalog = [
  { key: "CONOP", label: "CONOP", description: "Weekly operation CONOP file or external link." },
  { key: "OPORD", label: "OPORD", description: "Operation order link or uploaded PDF." },
  { key: "PLAYER_PRIMER", label: "Player Primer", description: "Member-facing primer or prep document." },
  { key: "ARMA3_PRESET", label: "Arma 3 Preset", description: "Arma 3 Launcher HTML preset file." },
  { key: "MAP", label: "AO Map", description: "Area of operations map or map pack." },
  { key: "INTELLIGENCE", label: "Intelligence", description: "Intel brief, imagery, or reference material." },
  { key: "RADIO_PLAN", label: "Radio Plan", description: "Radio plan, frequency card, or comms reference." },
  { key: "BRIEFING", label: "Briefing", description: "Briefing document or presentation." },
  { key: "MOD_COLLECTION", label: "Mod Collection", description: "Steam Workshop collection or mod list." },
  { key: "DOCUMENT", label: "Document", description: "General deployment document." },
  { key: "IMAGE", label: "Image", description: "Deployment image or visual reference." },
  { key: "VIDEO", label: "Video", description: "Video briefing or reference." },
  { key: "OTHER", label: "Other", description: "Other deployment resource." },
] as const satisfies readonly CatalogEntry[];

export const deploymentResourceVisibilityCatalog = [
  { key: "members", label: "Members", description: "Visible to members as the current active version." },
  { key: "staff", label: "Staff", description: "Visible to staff/admins only." },
  { key: "admin", label: "Admin", description: "Visible to admins only." },
] as const satisfies readonly CatalogEntry[];

export const missionStatusCatalog = [
  {
    key: "draft",
    label: "Draft",
    description: "Operation record is being prepared by the owner or staff.",
  },
  {
    key: "s3-review",
    label: "S3 Review",
    description: "Operation is waiting for S3 review and approval.",
  },
  {
    key: "approved",
    label: "Approved",
    description: "Operation has been approved but is not yet published to the wider portal audience.",
  },
  {
    key: "published",
    label: "Published",
    description: "Operation is approved and published for member-facing visibility.",
  },
  {
    key: "completed",
    label: "Completed",
    description: "Operation occurred and is awaiting or supporting post-operation review.",
  },
  {
    key: "aar-submitted",
    label: "AAR Submitted",
    description: "An after-action review has been submitted for the operation or patrol.",
  },
  {
    key: "archived",
    label: "Archived",
    description: "Operation lifecycle is closed and retained for historical reporting.",
  },
] as const satisfies readonly CatalogEntry[];

export const conopStatusCatalog = [
  {
    key: "draft",
    label: "Draft",
    description: "CONOP is being drafted and reviewed internally.",
  },
  {
    key: "published",
    label: "Published",
    description: "CONOP is ready for operational reference.",
  },
] as const satisfies readonly CatalogEntry[];

export const aarStatusCatalog = [
  {
    key: "draft",
    label: "Draft",
    description: "AAR is being prepared and has not been submitted for review.",
  },
  {
    key: "submitted",
    label: "Submitted",
    description: "AAR has been submitted for S3 review.",
  },
  {
    key: "pending-map",
    label: "Pending Map Screenshot",
    description: "Patrol AAR report exists but is missing the required map screenshot.",
  },
  {
    key: "reviewed",
    label: "Reviewed",
    description: "AAR has been reviewed and finalized by staff.",
  },
] as const satisfies readonly CatalogEntry[];

export const attendanceStatusCatalog = {
  rsvp: ["yes", "no", "maybe"] as const,
  final: ["present", "absent", "excused", "late", "loa"] as const,
};

const permissionGroups = [
  {
    module: "core",
    category: "general",
    permissions: [
      { key: "core.dashboard.view", label: "View dashboard", description: "Access the main dashboard and summary widgets." },
      { key: "dashboard.widgets.manage", label: "Manage dashboard widgets", description: "Manage reusable dashboard widget registration and shared widget settings." },
      { key: "core.search.use", label: "Use global search", description: "Use command palette and search-first navigation tools." },
      { key: "core.notifications.view", label: "View notifications", description: "View notification center activity and delivery summaries." },
      { key: "rules.view", label: "View rule results", description: "View rule engine summaries and provider result details." },
      { key: "rules.evaluate", label: "Evaluate rules", description: "Run rule engine evaluations where exposed by domain services." },
    ],
  },
  {
    module: "recommendations",
    category: "decision-support",
    permissions: [
      { key: "recommendations.view", label: "View recommendations", description: "View command decision support recommendations and history." },
      { key: "recommendations.manage", label: "Manage recommendations", description: "Dismiss, resolve, and manage recommendation lifecycle state." },
      { key: "operations.command.view", label: "View commander dashboard", description: "View the Commander Dashboard and command decision support summaries." },
      { key: "operations.command.manage", label: "Manage command assessments", description: "Manage commander intent assessments and command recommendation state." },
    ],
  },
  {
    module: "personnel",
    category: "profiles",
    permissions: [
      { key: "personnel.dashboard.view", label: "View Personnel Center", description: "Access the Personnel & Readiness Center overview and queues." },
      { key: "personnel.profile.view", label: "View profiles", description: "Open and inspect member profile records." },
      { key: "personnel.profile.create", label: "Create profiles", description: "Create new member profile records." },
      { key: "personnel.profile.edit", label: "Edit profiles", description: "Edit core member profile details." },
      { key: "personnel.profile.archive", label: "Archive profiles", description: "Archive or retire member profile records." },
      { key: "personnel.profile.status_change", label: "Change profile status", description: "Change a member profile status classification." },
      { key: "personnel.profile.service_record.view", label: "View service records", description: "View service record history and official personnel data." },
      { key: "personnel.profile.service_record.edit", label: "Edit service records", description: "Edit service record and personnel history details." },
      { key: "personnel.profile.notes.view", label: "View profile notes", description: "View permission-restricted profile notes." },
      { key: "personnel.profile.notes.create", label: "Create profile notes", description: "Create permission-restricted profile notes." },
      { key: "personnel.profile.notes.edit", label: "Edit profile notes", description: "Edit existing profile notes." },
      { key: "personnel.profile.notes.delete", label: "Delete profile notes", description: "Delete profile notes when permitted by policy." },
      { key: "personnel.profile.notes.manage", label: "Manage profile notes", description: "Manage restricted profile notes through approved staff workflows." },
      { key: "personnel.profile.logs.view", label: "View profile logs", description: "Review profile-level logs and history entries." },
      { key: "personnel.timeline.view", label: "View personnel timeline", description: "View member service timelines and assignment history." },
      { key: "personnel.actions.view", label: "View personnel actions", description: "View personnel action queues and follow-up items." },
      { key: "personnel.actions.manage", label: "Manage personnel actions", description: "Create, assign, and resolve personnel action items." },
    ],
  },
  {
    module: "roster",
    category: "assignments",
    permissions: [
      { key: "roster.member.view", label: "View roster", description: "View roster assignments and unit placement data." },
      { key: "roster.member.create", label: "Create roster entries", description: "Create roster entries or assignments for members." },
      { key: "roster.member.edit", label: "Edit roster entries", description: "Edit current roster assignments and member placement." },
      { key: "roster.member.archive", label: "Archive roster entries", description: "Archive roster entries that should no longer be active." },
      { key: "roster.rank.change", label: "Change rank", description: "Change a member's current rank." },
      { key: "roster.unit.assign", label: "Assign unit", description: "Assign or transfer a member to a unit." },
      { key: "roster.position.assign", label: "Assign position", description: "Assign or reassign a member to a position." },
      { key: "roster.status.change", label: "Change roster status", description: "Change roster and readiness status indicators." },
      { key: "roster.transfer.request", label: "Request transfer", description: "Request a roster transfer between units or assignments." },
      { key: "roster.transfer.approve", label: "Approve transfer", description: "Approve a pending roster transfer." },
      { key: "roster.transfer.reject", label: "Reject transfer", description: "Reject a pending roster transfer." },
      { key: "roster.bulk_update", label: "Bulk update roster", description: "Perform bulk roster updates for administrative workflows." },
    ],
  },
  {
    module: "units",
    category: "structure",
    permissions: [
      { key: "units.view", label: "View units", description: "View unit hierarchy and roster overview information." },
      { key: "units.create", label: "Create units", description: "Create units within the command hierarchy." },
      { key: "units.edit", label: "Edit units", description: "Edit unit metadata and organization details." },
      { key: "units.manage", label: "Manage units", description: "Manage unit metadata, structure, and operating policies." },
      { key: "units.archive", label: "Archive units", description: "Archive or deactivate units." },
      { key: "units.hierarchy.manage", label: "Manage unit hierarchy", description: "Manage parent and child unit relationships." },
      { key: "units.positions.view", label: "View positions", description: "View unit positions and billet definitions." },
      { key: "units.positions.create", label: "Create positions", description: "Create new unit positions or billets." },
      { key: "units.positions.edit", label: "Edit positions", description: "Edit unit position definitions." },
      { key: "units.positions.archive", label: "Archive positions", description: "Archive no-longer-used positions." },
      { key: "units.slots.view", label: "View unit slots", description: "View unit slot and billet availability." },
      { key: "units.slots.manage", label: "Manage unit slots", description: "Manage slot occupancy and billet readiness." },
      { key: "units.dashboard.view", label: "View unit dashboards", description: "Access unit-specific dashboard views." },
      { key: "unit.readiness.view", label: "View unit readiness", description: "View unit-scoped readiness, attendance, and qualification signals." },
      { key: "units.readiness.view", label: "View unit readiness", description: "View unit-scoped readiness, attendance, and qualification signals." },
      { key: "unit.requirements.manage", label: "Manage unit requirements", description: "Manage unit-specific readiness and qualification requirement timelines." },
      { key: "units.requirements.manage", label: "Manage unit requirements", description: "Manage unit-specific readiness and qualification requirement timelines." },
      { key: "units.assignments.manage", label: "Manage unit assignments", description: "Manage member assignment movement for units and billets." },
      { key: "units.positions.manage", label: "Manage positions", description: "Manage unit positions, billet expectations, and vacancy tracking." },
    ],
  },
  {
    module: "qualifications",
    category: "readiness",
    permissions: [
      { key: "qualifications.view", label: "View qualifications", description: "View qualification catalog and summary details." },
      { key: "qualifications.create", label: "Create qualifications", description: "Create qualification catalog entries." },
      { key: "qualifications.edit", label: "Edit qualifications", description: "Edit qualification definitions and metadata." },
      { key: "qualifications.manage", label: "Manage qualifications", description: "Manage qualification catalog records and readiness configuration." },
      { key: "qualifications.archive", label: "Archive qualifications", description: "Archive qualification definitions." },
      { key: "qualifications.categories.manage", label: "Manage qualification categories", description: "Manage qualification category groupings." },
      { key: "qualifications.record.view", label: "View qualification records", description: "View qualification records awarded to members." },
      { key: "qualifications.record.award", label: "Award qualifications", description: "Award qualifications to members." },
      { key: "qualifications.record.revoke", label: "Revoke qualifications", description: "Revoke or invalidate member qualifications." },
      { key: "qualifications.record.edit", label: "Edit qualification records", description: "Edit awarded qualification records." },
      { key: "qualifications.records.view", label: "View qualification records", description: "Alias permission for viewing member qualification records." },
      { key: "qualifications.records.award", label: "Award qualification records", description: "Alias permission for awarding member qualification records." },
      { key: "qualifications.records.revoke", label: "Revoke qualification records", description: "Alias permission for revoking member qualification records." },
      { key: "qualifications.matrix.view", label: "View qualification matrix", description: "View readiness matrix across members and units." },
      { key: "qualifications.requirements.view", label: "View qualification requirements", description: "View unit and position qualification requirements." },
      { key: "qualifications.requirements.manage", label: "Manage qualification requirements", description: "Manage unit and position qualification requirements." },
      { key: "qualifications.signoff.manage", label: "Manage qualification signoff", description: "Manage instructor signoff and certification workflows." },
    ],
  },
  {
    module: "forms",
    category: "workflow",
    permissions: [
      { key: "forms.view", label: "View forms", description: "View application templates and submission summaries." },
      { key: "forms.create", label: "Create forms", description: "Create application and request form templates." },
      { key: "forms.edit", label: "Edit forms", description: "Edit form templates, fields, and workflow metadata." },
      { key: "forms.archive", label: "Archive forms", description: "Archive or disable form templates." },
      { key: "forms.submit", label: "Submit forms", description: "Create and submit member-facing applications or requests." },
      { key: "forms.review", label: "Review submissions", description: "View and work staff review queues for form submissions." },
      { key: "forms.approve", label: "Approve submissions", description: "Approve form submissions and advance workflow state." },
      { key: "forms.deny", label: "Deny submissions", description: "Deny or reject form submissions." },
      { key: "forms.comment", label: "Comment on submissions", description: "Comment on form submissions and review threads." },
      { key: "forms.assign_reviewer", label: "Assign reviewers", description: "Assign or change reviewers for workflow submissions." },
      { key: "forms.admin", label: "Administer forms", description: "Full administrative access across templates, submissions, and workflow settings." },
    ],
  },
  {
    module: "events",
    category: "operations",
    permissions: [
      { key: "events.view", label: "View events", description: "View operations and training events." },
      { key: "events.create", label: "Create events", description: "Create event records." },
      { key: "events.edit", label: "Edit events", description: "Edit event scheduling and metadata." },
      { key: "events.delete", label: "Delete events", description: "Delete or remove events from the calendar." },
      { key: "events.publish", label: "Publish events", description: "Publish events to members and downstream clients." },
      { key: "events.cancel", label: "Cancel events", description: "Cancel scheduled events." },
      { key: "events.archive", label: "Archive events", description: "Archive past or retired events." },
      { key: "events.calendar.view", label: "View event calendar", description: "View calendar-oriented event scheduling surfaces." },
      { key: "operations.package.view", label: "View operations packages", description: "View planning packages for deployment weeks." },
      { key: "operations.package.edit", label: "Edit operations packages", description: "Prepare and maintain planning packages for deployment weeks." },
      { key: "operations.package.review", label: "Review operations packages", description: "Review Operations Package readiness and package validation state." },
      { key: "operations.package.approve", label: "Approve operations packages", description: "Approve Operations Packages for release workflows." },
      { key: "operations.package.publish", label: "Publish operations packages", description: "Publish Operations Packages when publishing workflows are enabled." },
      { key: "operations.planning.view", label: "View operations planning", description: "View S3 planning notes and operational-week context." },
      { key: "operations.planning.edit", label: "Edit operations planning", description: "Edit S3 planning notes and operational-week context." },
      { key: "operations.readiness.view", label: "View operations readiness", description: "View Operations Package readiness scores and validation issues." },
      { key: "operations.readiness.evaluate", label: "Evaluate operations readiness", description: "Run Operations Package readiness checks." },
      { key: "operations.health.view", label: "View operational health", description: "View Operations Health scores, health rules, and recommendations." },
      { key: "operations.health.manage", label: "Manage operational health", description: "Manage operational health rule configuration and provider-owned review actions." },
      { key: "operations.release.view", label: "View operations releases", description: "View published Operations Release records." },
      { key: "operations.release.publish", label: "Publish operations releases", description: "Publish Operations Releases to configured delivery channels." },
      { key: "operations.release.history", label: "View operations release history", description: "View Operations Release history and amendment records." },
      { key: "operations.tasking.view", label: "View weekly tasking", description: "View operation-linked weekly tasking and unit tasking." },
      { key: "operations.tasking.manage", label: "Manage weekly tasking", description: "Create and edit weekly operation tasking." },
      { key: "operations.resources.manage", label: "Manage operations resources", description: "Attach and manage planning resources for operational weeks." },
      { key: "operations.zeus.assign", label: "Assign operations Zeus", description: "Assign or change Zeus ownership for operational planning." },
      { key: "operations.center.view", label: "View Operations Center", description: "View the Operations Center dashboard and command queues." },
      { key: "operations.dashboard.customize", label: "Customize Operations dashboard", description: "Customize personal Operations Center widget layout and collapsed state." },
      { key: "operations.recommendations.view", label: "View operations recommendations", description: "View operations-scoped command recommendations and related inspectors." },
      { key: "patrols.view", label: "View patrols", description: "View lightweight patrol records, participants, and AAR state." },
      { key: "patrols.create", label: "Start patrols", description: "Start lightweight patrol events through the portal operation workflow." },
      { key: "patrols.lead", label: "Lead patrols", description: "Be assigned as or act as a patrol leader for portal patrol events." },
      { key: "patrols.complete", label: "Complete patrols", description: "Mark a running patrol complete and move it into AAR follow-up." },
      { key: "patrols.participants.manage", label: "Manage patrol participants", description: "Manually add or remove confirmed patrol participants." },
      { key: "patrols.rsvp", label: "RSVP to patrols", description: "Record lightweight patrol interest without marking final attendance." },
      { key: "patrols.aar.submit", label: "Submit patrol AARs", description: "Submit required Patrol AAR reports and screenshots." },
      { key: "patrols.aar.review", label: "Review patrol AARs", description: "Review Patrol AARs and progression recommendations." },
      { key: "patrols.archive", label: "Archive patrols", description: "Archive patrol records after review." },
      { key: "aars.submit", label: "Submit AARs", description: "Submit patrol after-action reviews." },
      { key: "aars.review", label: "Review AARs", description: "Review submitted after-action reviews." },
      { key: "aars.attachments.manage", label: "Manage AAR attachments", description: "Upload and manage Patrol AAR screenshots and supporting media." },
    ],
  },
  {
    module: "attendance",
    category: "tracking",
    permissions: [
      { key: "attendance.view", label: "View attendance", description: "View attendance and RSVP records." },
      { key: "attendance.manage", label: "Manage attendance", description: "Manage attendance workflows and unit-scoped policy interpretation." },
      { key: "attendance.rsvp.view", label: "View RSVP state", description: "View RSVP status for events." },
      { key: "attendance.rsvp.manage", label: "Manage RSVP state", description: "Manage RSVP state on behalf of members." },
      { key: "attendance.record", label: "Record attendance", description: "Record final attendance results." },
      { key: "attendance.edit", label: "Edit attendance", description: "Edit attendance records after initial entry." },
      { key: "attendance.override", label: "Override attendance", description: "Override attendance results for sensitive corrections." },
      { key: "attendance.lock", label: "Lock attendance", description: "Lock attendance records after closeout." },
      { key: "attendance.reports.view", label: "View attendance reports", description: "View attendance reporting and trend surfaces." },
      { key: "attendance.policies.manage", label: "Manage attendance policies", description: "Configure unit-scoped attendance policy thresholds and review guidance." },
    ],
  },
  {
    module: "readiness",
    category: "personnel",
    permissions: [
      { key: "readiness.member.view", label: "View member readiness", description: "View explainable member readiness rule results." },
      { key: "readiness.unit.view", label: "View unit readiness", description: "View explainable unit readiness rule results." },
    ],
  },
  {
    module: "transfers",
    category: "personnel",
    permissions: [
      { key: "transfers.view", label: "View transfers", description: "View personnel transfer requests and review state." },
      { key: "transfers.submit", label: "Submit transfers", description: "Submit a member transfer request for staff review." },
      { key: "transfers.review", label: "Review transfers", description: "Approve or deny transfer requests through case-backed workflows." },
    ],
  },
  {
    module: "loa",
    category: "personnel",
    permissions: [
      { key: "loa.view", label: "View LOA", description: "View leave of absence records and return queues." },
      { key: "loa.submit", label: "Submit LOA", description: "Submit leave of absence requests." },
      { key: "loa.review", label: "Review LOA", description: "Approve, deny, or mark return from leave of absence." },
    ],
  },
  {
    module: "campaigns",
    category: "operations",
    permissions: [
      { key: "campaigns.view", label: "View deployments", description: "View deployment summaries and detail pages." },
      { key: "campaigns.create", label: "Create deployments", description: "Create deployments and planning records." },
      { key: "campaigns.edit", label: "Edit deployments", description: "Edit deployment metadata and narrative details." },
      { key: "campaigns.publish", label: "Publish deployments", description: "Publish deployment updates." },
      { key: "campaigns.archive", label: "Archive deployments", description: "Archive completed or retired deployments." },
      { key: "campaigns.timeline.manage", label: "Manage deployment timeline", description: "Manage deployment timeline entries and operation type/phase tracking." },
      { key: "campaigns.statistics.view", label: "View deployment statistics", description: "View deployment participation and readiness statistics." },
      { key: "campaigns.documents.manage", label: "Manage deployment documents", description: "Manage deployment-related planning and archival documents." },
      { key: "deployments.create", label: "Create deployments", description: "Create configurable multi-week deployment records." },
      { key: "deployments.edit", label: "Edit deployments", description: "Edit deployment metadata, duration, and Zeus assignment." },
      { key: "deployments.publish", label: "Publish deployments", description: "Publish deployment records and related operation visibility." },
      { key: "deployments.resources.view", label: "View deployment resources", description: "View current deployment resource files and links." },
      { key: "deployments.resources.upload", label: "Upload deployment resources", description: "Upload deployment resource files and replacement versions." },
      { key: "deployments.resources.edit", label: "Edit deployment resources", description: "Edit deployment resource metadata and current version." },
      { key: "deployments.resources.delete", label: "Archive deployment resources", description: "Archive deployment resources and old versions." },
      { key: "deployments.progression.view", label: "View deployment progression", description: "View AAR-informed deployment progression recommendations and planning notes." },
      { key: "deployments.progression.manage", label: "Manage deployment progression", description: "Record progression decisions, next-operation recommendations, and planning notes." },
    ],
  },
  {
    module: "s3",
    category: "staff-operations",
    permissions: [
      { key: "s3.dashboard.view", label: "View S3 dashboard", description: "Access the S3 oversight dashboard." },
      { key: "s3.missions.view", label: "View operations", description: "View S3 operation planning records." },
      { key: "s3.missions.create", label: "Create operations", description: "Create draft operation planning records." },
      { key: "s3.missions.edit", label: "Edit operations", description: "Edit operation planning records." },
      { key: "s3.missions.review", label: "Review operations", description: "Review pending operation planning work." },
      { key: "s3.missions.approve", label: "Approve operations", description: "Approve operation planning work." },
      { key: "s3.missions.reject", label: "Reject operations", description: "Reject or return operation planning work." },
      { key: "s3.missions.publish", label: "Publish operations", description: "Publish approved operations." },
      { key: "s3.missions.archive", label: "Archive operations", description: "Archive older or superseded operation records." },
      { key: "s3.conops.view", label: "View CONOPs", description: "View concept-of-operations content." },
      { key: "s3.conops.create", label: "Create CONOPs", description: "Create concept-of-operations records." },
      { key: "s3.conops.edit", label: "Edit CONOPs", description: "Edit concept-of-operations records." },
      { key: "s3.conops.publish", label: "Publish CONOPs", description: "Publish concept-of-operations records." },
      { key: "s3.aars.view", label: "View AARs", description: "View after-action review content." },
      { key: "s3.aars.submit", label: "Submit AARs", description: "Submit after-action review records." },
      { key: "s3.aars.review", label: "Review AARs", description: "Review after-action review submissions." },
      { key: "s3.zeus.assign", label: "Assign Zeus", description: "Assign or change deployment and operation Zeus ownership." },
    ],
  },
  {
    module: "documents",
    category: "content",
    permissions: [
      { key: "documents.view", label: "View documents", description: "View documents and guides." },
      { key: "documents.create", label: "Create documents", description: "Create managed document records." },
      { key: "documents.edit", label: "Edit documents", description: "Edit managed document records." },
      { key: "documents.delete", label: "Delete documents", description: "Delete document records when policy permits removal." },
      { key: "documents.archive", label: "Archive documents", description: "Archive or retire documents." },
      { key: "documents.publish", label: "Publish documents", description: "Publish documents to the portal." },
      { key: "documents.restrict", label: "Restrict documents", description: "Restrict document access or visibility." },
      { key: "documents.attachments.manage", label: "Manage document attachments", description: "Add, remove, and manage document attachments." },
      { key: "documents.categories.manage", label: "Manage document categories", description: "Manage document categories and organization." },
      { key: "documents.review.manage", label: "Manage document reviews", description: "Manage review dates and document review workflows." },
      { key: "documents.readreceipts.view", label: "View document read receipts", description: "View document acknowledgement and read-receipt records." },
      { key: "documents.permissions.manage", label: "Manage document permissions", description: "Manage document-specific access rules and permission rows." },
    ],
  },
  {
    module: "community",
    category: "case-management",
    permissions: [
      { key: "community.view", label: "View Community Management", description: "Access the Community Management Center." },
      { key: "community.manage", label: "Manage Community Management", description: "Manage community management settings and workflows." },
      { key: "community.dashboard.view", label: "View community dashboard", description: "View community health indicators and case queues." },
      { key: "cases.view", label: "View cases", description: "View community case records according to confidentiality scope." },
      { key: "cases.create", label: "Create cases", description: "Create community case records." },
      { key: "cases.edit", label: "Edit cases", description: "Edit community case details." },
      { key: "cases.assign", label: "Assign cases", description: "Assign and reassign case ownership." },
      { key: "cases.transition", label: "Transition cases", description: "Move cases through valid workflow transitions." },
      { key: "cases.close", label: "Close cases", description: "Record decisions and close or resolve cases." },
      { key: "cases.reopen", label: "Reopen cases", description: "Reopen closed community cases when policy allows." },
      { key: "cases.archive", label: "Archive cases", description: "Archive retained case history." },
      { key: "cases.restricted.view", label: "View restricted cases", description: "View restricted or administrator-level case content." },
      { key: "cases.command.view", label: "View command cases", description: "View command-only case content." },
      { key: "evidence.view", label: "View evidence", description: "View case evidence metadata and links." },
      { key: "evidence.manage", label: "Manage evidence", description: "Add evidence and update evidence status without hard deletion." },
      { key: "notes.view", label: "View case notes", description: "View case notes according to visibility scope." },
      { key: "notes.manage", label: "Manage case notes", description: "Add staff, command, administrative, and private notes." },
      { key: "incidents.view", label: "View incident reports", description: "View incident reports and related cases." },
      { key: "incidents.create", label: "Create incident reports", description: "Submit incident reports into the case engine." },
      { key: "incidents.manage", label: "Manage incident reports", description: "Manage incident review records and follow-up." },
      { key: "appeals.view", label: "View appeals", description: "View appeal cases and review queues." },
      { key: "appeals.submit", label: "Submit appeals", description: "Submit appeals against case decisions or moderation actions." },
      { key: "appeals.review", label: "Review appeals", description: "Review and decide appeal cases." },
      { key: "moderation.view", label: "View moderation", description: "View moderation records and queues." },
      { key: "moderation.warn", label: "Issue warnings", description: "Issue portal-recorded warnings through Community Management." },
      { key: "moderation.kick", label: "Kick members", description: "Request or execute Discord kick actions through portal workflow." },
      { key: "moderation.timeout", label: "Timeout members", description: "Request timeout or timeout reversal actions." },
      { key: "moderation.ban", label: "Ban members", description: "Request ban or unban actions." },
      { key: "moderation.reverse", label: "Reverse moderation", description: "Reverse or supersede moderation actions when policy permits." },
      { key: "moderation.history.view", label: "View moderation history", description: "View moderation action history and failures." },
    ],
  },
  {
    module: "notifications",
    category: "delivery",
    permissions: [
      { key: "notifications.view", label: "View notifications", description: "View notification records and summaries." },
      { key: "notifications.manage", label: "Manage notifications", description: "Manage notification state and settings." },
      { key: "notifications.send", label: "Send notifications", description: "Send manual or automated notifications." },
      { key: "notifications.templates.manage", label: "Manage notification templates", description: "Manage reusable notification templates." },
      { key: "notifications.delivery.view", label: "View notification delivery", description: "View notification delivery results." },
      { key: "notifications.delivery.retry", label: "Retry notification delivery", description: "Retry failed notification deliveries." },
    ],
  },
  {
    module: "communications",
    category: "pipeline",
    permissions: [
      { key: "communications.view", label: "View Communications Center", description: "View communication history, announcements, delivery health, templates, and preferences." },
      { key: "communications.manage", label: "Manage communications", description: "Manage scheduled communication state and pipeline administration." },
      { key: "communications.send", label: "Send communications", description: "Request outbound communication through the unified pipeline." },
      { key: "communications.retry", label: "Retry communications", description: "Retry failed communication deliveries through the pipeline." },
      { key: "communications.history.view", label: "View communication history", description: "View permanent communication request and delivery history." },
      { key: "communications.routing.view", label: "View communication routing", description: "View communication domain routing, resolved guilds, mapped channels, and routing warnings." },
      { key: "communications.routing.manage", label: "Manage communication routing", description: "Manage communication domain routing and guild delivery policy." },
      { key: "communications.delivery.view", label: "View communication deliveries", description: "View communication delivery queue, attempts, failures, and provider history." },
      { key: "communications.health.view", label: "View communication health", description: "View communication platform health, missing mappings, failed delivery rate, and backlog." },
      { key: "communications.templates.manage", label: "Manage communication templates", description: "Create and update communication templates." },
      { key: "communications.preferences.manage", label: "Manage communication preferences", description: "Manage communication delivery preferences." },
      { key: "announcements.view", label: "View announcements", description: "View announcement drafts, sent announcements, and history." },
      { key: "announcements.manage", label: "Manage announcements", description: "Create and edit announcement drafts." },
      { key: "announcements.send", label: "Send announcements", description: "Send announcements through the unified communication pipeline." },
    ],
  },
  {
    module: "discord",
    category: "integration",
    permissions: [
      { key: "discord.view", label: "View Discord settings", description: "View Discord integration settings and health." },
      { key: "discord.manage", label: "Manage Discord settings", description: "Manage Discord integration settings." },
      { key: "discord.servers.manage", label: "Manage Discord servers", description: "Manage Discord server mappings." },
      { key: "discord.guilds.manage", label: "Manage Discord guilds", description: "Manage Discord guild platform records, type, status, and primary community guild policy." },
      { key: "discord.guilds.discover", label: "Discover Discord guilds", description: "Run Discord guild discovery and inventory import without overwriting administrator mappings." },
      { key: "discord.guilds.health.view", label: "View Discord guild health", description: "View per-guild REST, Gateway, interaction, permissions, and synchronization health." },
      { key: "discord.guilds.diagnostics.view", label: "View Discord guild diagnostics", description: "View safe multi-guild diagnostics, missing channels, missing roles, and configuration problems." },
      { key: "discord.guilds.audit.view", label: "View Discord guild audit", description: "View per-guild Discord configuration, synchronization, Gateway, REST, and administrator audit history." },
      { key: "discord.discovery.view", label: "View Discord discovery", description: "View Discord discovery sessions, snapshots, resource changes, and scan history." },
      { key: "discord.discovery.run", label: "Run Discord discovery", description: "Run full, targeted, dry-run, and repair-oriented Discord resource discovery scans." },
      { key: "discord.discovery.cancel", label: "Cancel Discord discovery", description: "Cancel queued or running Discord discovery sessions when supported." },
      { key: "discord.resources.view", label: "View Discord resources", description: "View discovered Discord channels, roles, events, emojis, stickers, and capability metadata." },
      { key: "discord.resources.manage", label: "Manage Discord resources", description: "Manage portal-owned metadata and administrator decisions for discovered Discord resources." },
      { key: "discord.reconciliation.view", label: "View Discord reconciliation", description: "View detected Discord resource drift, missing resources, and mapping impact analysis." },
      { key: "discord.reconciliation.manage", label: "Manage Discord reconciliation", description: "Resolve, ignore, disable mapping, and remap Discord reconciliation items." },
      { key: "discord.sync.schedule.manage", label: "Manage Discord sync schedules", description: "Manage scheduled and Gateway-driven Discord discovery and synchronization policy." },
      { key: "discord.mappings.manage", label: "Manage Discord mappings", description: "Manage explicit Discord resource mappings used by portal communication and automation workflows." },
      { key: "discord.automation.view", label: "View Discord automation", description: "View Discord automation definitions, previews, approvals, executions, and drift." },
      { key: "discord.automation.manage", label: "Manage Discord automation", description: "Create, update, enable, disable, and synchronize Discord automation definitions." },
      { key: "discord.automation.preview", label: "Preview Discord automation", description: "Run dry-run previews for Discord automation without changing Discord state." },
      { key: "discord.automation.approve", label: "Approve Discord automation", description: "Approve or reject manual Discord automation execution plans." },
      { key: "discord.automation.execute", label: "Execute Discord automation", description: "Run approved Discord automation actions against managed guilds." },
      { key: "discord.automation.retry", label: "Retry Discord automation", description: "Retry failed Discord automation actions where retry is safe." },
      { key: "discord.automation.rollback", label: "Rollback Discord automation", description: "Request explicit compensation or rollback workflows for Discord automation." },
      { key: "discord.automation.exceptions.view", label: "View Discord automation exceptions", description: "View member, guild, role, and automation exceptions." },
      { key: "discord.automation.exceptions.manage", label: "Manage Discord automation exceptions", description: "Create and expire explicit Discord automation exceptions." },
      { key: "discord.automation.history.view", label: "View Discord automation history", description: "View Discord automation execution, action, retry, and managed-role history." },
      { key: "discord.events.view", label: "View Discord events", description: "View Portal-managed Discord Scheduled Event links, plans, and synchronization state." },
      { key: "discord.events.manage", label: "Manage Discord events", description: "Manage Discord Scheduled Event plans and link configuration." },
      { key: "discord.events.preview", label: "Preview Discord events", description: "Generate multi-guild Discord Scheduled Event plans without modifying Discord." },
      { key: "discord.events.publish", label: "Publish Discord events", description: "Create or update Discord Scheduled Events through approved Portal plans." },
      { key: "discord.events.update", label: "Update Discord events", description: "Synchronize Portal-owned event changes to linked Discord Scheduled Events." },
      { key: "discord.events.cancel", label: "Cancel Discord events", description: "Cancel linked Discord Scheduled Events while preserving Portal history." },
      { key: "discord.events.approve", label: "Approve Discord event plans", description: "Approve manual Discord Scheduled Event plans before execution." },
      { key: "discord.events.retry", label: "Retry Discord event actions", description: "Retry failed guild-specific Discord Scheduled Event actions." },
      { key: "discord.events.reconcile", label: "Reconcile Discord events", description: "Review drift and reapply Portal state to linked Discord Scheduled Events." },
      { key: "discord.events.templates.view", label: "View Discord event templates", description: "View Scheduled Event title and description templates." },
      { key: "discord.events.templates.manage", label: "Manage Discord event templates", description: "Manage versioned Discord Scheduled Event templates." },
      { key: "discord.events.policies.view", label: "View Discord event policies", description: "View per-guild event integration policies." },
      { key: "discord.events.policies.manage", label: "Manage Discord event policies", description: "Manage per-guild event integration, entity type, approval, and RSVP import policy." },
      { key: "discord.events.participation.view", label: "View Discord event participation", description: "View Discord Scheduled Event interest observations as non-authoritative participation signals." },
      { key: "discord.events.participation.manage", label: "Manage Discord event participation", description: "Manage Discord event participation observations without finalizing attendance." },
      { key: "discord.events.diagnostics.view", label: "View Discord event diagnostics", description: "View event synchronization drift, failures, and partial success state." },
      { key: "discord.events.history.view", label: "View Discord event history", description: "View Discord Scheduled Event plan, execution, link, and drift history." },
      { key: "discord.communications.view", label: "View Discord communications", description: "View Discord communication routing, domain mappings, deliveries, and health." },
      { key: "discord.communications.manage", label: "Manage Discord communications", description: "Manage Discord communication routing policy and domain-to-channel mappings." },
      { key: "qualifications.discord_automation.view", label: "View qualification Discord automation", description: "View Discord role automation attached to qualifications." },
      { key: "qualifications.discord_automation.manage", label: "Manage qualification Discord automation", description: "Manage qualification-to-Discord-role automation policy." },
      { key: "personnel.discord_automation.view", label: "View personnel Discord automation", description: "View member-level Discord automation state, drift, and managed roles." },
      { key: "discord.channels.manage", label: "Manage Discord channels", description: "Manage Discord channel mappings." },
      { key: "discord.roles.manage", label: "Manage Discord roles", description: "Manage Discord role mappings." },
      { key: "discord.members.view", label: "View Discord members", description: "View linked Discord member state and sync status." },
      { key: "discord.members.sync", label: "Sync Discord members", description: "Run Discord guild member import and drift-correction sync." },
      { key: "discord.identity.view", label: "View Discord identities", description: "View Discord identity diagnostics, duplicate warnings, and OAuth/import link health." },
      { key: "discord.identity.merge", label: "Merge Discord identities", description: "Merge exact Discord ID duplicate portal identities without authorizing by role names." },
      { key: "discord.gateway.view", label: "View Discord Gateway", description: "View Discord Gateway worker configuration and runtime status." },
      { key: "discord.gateway.manage", label: "Manage Discord Gateway", description: "Manage Discord Gateway configuration where supported by deployment policy." },
      { key: "discord.gateway.health.view", label: "View Discord Gateway health", description: "View Gateway connection, latency, intents, and reconnect diagnostics." },
      { key: "discord.gateway.events.view", label: "View Discord Gateway events", description: "View recent sanitized Gateway event logs and failures." },
      { key: "discord.gateway.events.retry", label: "Retry Discord Gateway events", description: "Retry failed Gateway events after configuration or data corrections." },
      { key: "discord.gateway.events.resolve", label: "Resolve Discord Gateway events", description: "Mark failed Gateway events resolved, ignored, or superseded after review." },
      { key: "discord.gateway.handlers.view", label: "View Discord Gateway handlers", description: "View Gateway handler registry, required intents, ownership, and enabled state." },
      { key: "discord.gateway.handlers.manage", label: "Manage Discord Gateway handlers", description: "Manage Gateway handler enablement and policy when supported." },
      { key: "discord.gateway.metrics.view", label: "View Discord Gateway metrics", description: "View Gateway queue, reconnect, failure, and handler metrics." },
      { key: "discord.gateway.voice.view", label: "View Gateway voice awareness", description: "View Gateway voice-awareness suggestions and diagnostics." },
      { key: "discord.gateway.voice.manage", label: "Manage Gateway voice awareness", description: "Manage Patrol voice-channel association and suggestion policy." },
      { key: "discord.gateway.attachments.view", label: "View Gateway attachment continuation", description: "View scoped Gateway attachment-continuation diagnostics." },
      { key: "discord.gateway.diagnostics.view", label: "View Gateway diagnostics", description: "View safe Gateway diagnostics, failed event summaries, and intent health." },
      { key: "discord.gateway.configuration.manage", label: "Manage Gateway configuration", description: "Manage Gateway configuration policy where deployment supports it." },
      { key: "discord.gateway.restart", label: "Restart Discord Gateway", description: "Request Gateway restart only when infrastructure supports it." },
      { key: "discord.notifications.send", label: "Send Discord notifications", description: "Send portal notifications to Discord destinations." },
      { key: "discord.voice.view", label: "View Discord voice awareness", description: "View non-authoritative Discord voice presence suggestions." },
      { key: "discord.voice.manage", label: "Manage Discord voice awareness", description: "Manage voice awareness settings and patrol suggestion policies." },
      { key: "discord.roles.sync", label: "Sync Discord roles", description: "Run explicitly mapped Discord role synchronization." },
      { key: "discord.nicknames.sync", label: "Sync Discord nicknames", description: "Preview or run configured nickname synchronization when enabled." },
      { key: "discord.guilds.manage", label: "Manage Discord guild policy", description: "Manage primary/secondary guild policy and Gateway event settings." },
      { key: "discord.diagnostics.view", label: "View Discord diagnostics", description: "View safe Discord configuration, Gateway, REST, and webhook diagnostics." },
      { key: "discord.patrols.create", label: "Start Discord patrols", description: "Start portal Patrols from Discord commands." },
      { key: "discord.patrols.manage", label: "Manage Discord patrols", description: "Complete patrols and manage patrol workflows from Discord commands." },
      { key: "discord.sync.run", label: "Run Discord sync", description: "Run Discord synchronization jobs." },
      { key: "discord.sync.view", label: "View Discord sync", description: "View Discord synchronization state and history." },
      { key: "discord.moderation.view", label: "View Discord moderation", description: "View case-backed Discord moderation policy, actions, appeals, and diagnostics." },
      { key: "discord.moderation.warn", label: "Warn Discord members", description: "Record Portal-owned warnings against Discord identities through Community Cases." },
      { key: "discord.moderation.timeout", label: "Timeout Discord members", description: "Apply or remove Discord member timeout when moderation policy allows it." },
      { key: "discord.moderation.kick", label: "Kick Discord members", description: "Kick mapped Discord members with required reason and audit logging." },
      { key: "discord.moderation.ban", label: "Ban Discord members", description: "Ban or unban mapped Discord members when moderation policy allows it." },
      { key: "discord.moderation.appeals", label: "Review Discord moderation appeals", description: "View and review appeals attached to Discord moderation cases." },
      { key: "discord.moderation.policy.manage", label: "Manage Discord moderation policies", description: "Manage per-guild moderation policy, approval, evidence, and cross-guild behavior." },
      { key: "discord.moderation.case.manage", label: "Manage Discord moderation cases", description: "Attach notes, evidence, discussions, and moderation actions to Community Cases." },
      { key: "discord.moderation.history.view", label: "View Discord moderation history", description: "View Discord moderation action history." },
      { key: "discord.applications.view", label: "View Discord applications", description: "View Discord application integration state, catalog, policies, and history." },
      { key: "discord.applications.manage", label: "Manage Discord applications", description: "Manage Discord application integration settings and operator surfaces." },
      { key: "discord.applications.catalog.view", label: "View Discord application catalog", description: "View Portal-backed application entry points exposed to Discord." },
      { key: "discord.applications.catalog.manage", label: "Manage Discord application catalog", description: "Manage Discord application catalog entry availability and Phase 5 provider metadata." },
      { key: "discord.applications.policies.view", label: "View Discord application policies", description: "View per-guild application entry and review-routing policies." },
      { key: "discord.applications.policies.manage", label: "Manage Discord application policies", description: "Manage per-guild application visibility, channel, panel, and review settings." },
      { key: "discord.applications.panels.view", label: "View Discord application panels", description: "View persistent Discord application panel configuration and health." },
      { key: "discord.applications.panels.manage", label: "Manage Discord application panels", description: "Preview, publish, update, disable, or archive managed application panels." },
      { key: "discord.applications.review.view", label: "View Discord application review", description: "View Discord-routed application review messages and state." },
      { key: "discord.applications.review.assign", label: "Assign Discord application reviews", description: "Assign application reviewers from Discord quick actions through Portal permissions." },
      { key: "discord.applications.review.request_information", label: "Request application information", description: "Request more information from applicants through Portal-owned review actions." },
      { key: "discord.applications.review.approve", label: "Approve Discord application reviews", description: "Approve application reviews from Discord quick actions through Portal services." },
      { key: "discord.applications.review.deny", label: "Deny Discord application reviews", description: "Deny application reviews from Discord quick actions through Portal services." },
      { key: "discord.applications.sessions.view", label: "View Discord application sessions", description: "View application interaction sessions and continuation state." },
      { key: "discord.applications.sessions.manage", label: "Manage Discord application sessions", description: "Cancel, expire, or reconcile application interaction sessions." },
      { key: "discord.applications.diagnostics.view", label: "View Discord application diagnostics", description: "View application integration failures, routing health, and recommendations." },
      { key: "discord.applications.history.view", label: "View Discord application history", description: "View Discord application integration history and audit context." },
      { key: "discord.bot.health.view", label: "View Discord bot health", description: "View Discord bot health and status information." },
      { key: "admin.discord.manage", label: "Manage Discord administration", description: "Manage Discord administration surfaces and operator workflows." },
    ],
  },
  {
    module: "builder",
    category: "platform-builder",
    permissions: [
      { key: "builder.view", label: "View builder tools", description: "View platform builder tools and configuration surfaces." },
      { key: "builder.forms.manage", label: "Manage builder forms", description: "Manage form builder templates and fields." },
      { key: "builder.workflows.manage", label: "Manage workflow templates", description: "Manage workflow template foundations and approval routing." },
      { key: "builder.dashboards.manage", label: "Manage dashboard layouts", description: "Manage configurable dashboard layout foundations." },
      { key: "builder.widgets.manage", label: "Manage widget catalog", description: "Manage dashboard widget catalog visibility and configuration." },
      { key: "builder.automations.manage", label: "Manage automation rules", description: "Manage safe automation rule foundations and placeholders." },
    ],
  },
  {
    module: "admin",
    category: "administration",
    permissions: [
      { key: "admin.dashboard.view", label: "View admin dashboard", description: "View administration dashboard surfaces." },
      { key: "admin.users.view", label: "View users", description: "View portal user records." },
      { key: "admin.users.manage", label: "Manage users", description: "Manage portal users and profile linking." },
      { key: "admin.roles.view", label: "View roles", description: "View role and permission assignments." },
      { key: "admin.roles.create", label: "Create roles", description: "Create roles for the access model." },
      { key: "admin.roles.edit", label: "Edit roles", description: "Edit role metadata and membership." },
      { key: "admin.roles.delete", label: "Delete roles", description: "Delete or retire roles." },
      { key: "admin.permissions.view", label: "View permissions", description: "View the system-defined permission catalog." },
      { key: "admin.permissions.assign", label: "Assign permissions", description: "Assign permissions to roles." },
      { key: "admin.settings.view", label: "View system settings", description: "View system settings and configuration." },
      { key: "admin.settings.manage", label: "Manage system settings", description: "Manage system settings and configuration." },
    ],
  },
  {
    module: "audit",
    category: "compliance",
    permissions: [
      { key: "audit.view", label: "View audit logs", description: "View audit log entries and historical change records." },
      { key: "audit.export", label: "Export audit logs", description: "Export audit logs for compliance or reporting." },
    ],
  },
] as const satisfies readonly PermissionGroupDefinition[];

export const systemPermissionCatalog = permissionGroups.flatMap((group) =>
  group.permissions.map((permission) => ({
    ...permission,
    module: group.module,
    category: group.category,
    isSystem: true,
  })),
);

const memberPermissionKeys = [
  "core.dashboard.view",
  "core.search.use",
  "core.notifications.view",
  "personnel.dashboard.view",
  "personnel.profile.view",
  "personnel.profile.service_record.view",
  "personnel.timeline.view",
  "roster.member.view",
  "units.view",
  "units.dashboard.view",
  "readiness.member.view",
  "qualifications.view",
  "qualifications.record.view",
  "qualifications.records.view",
  "events.view",
  "events.calendar.view",
  "attendance.rsvp.view",
  "loa.submit",
  "transfers.submit",
  "patrols.view",
  "patrols.create",
  "patrols.lead",
  "patrols.rsvp",
  "patrols.aar.submit",
  "aars.submit",
  "campaigns.view",
  "deployments.resources.view",
  "documents.view",
  "forms.view",
  "forms.submit",
  "forms.comment",
] as const;

export const starterRolePresets: readonly StarterRolePreset[] = [
  {
    name: "member",
    label: "Member",
    description: "Baseline self-service access for ordinary members.",
    permissionKeys: memberPermissionKeys,
  },
  {
    name: "instructor",
    label: "Instructor",
    description: "Qualification-focused preset for trainers and signoff authorities.",
    permissionKeys: [
      ...memberPermissionKeys,
      "qualifications.record.award",
      "qualifications.record.edit",
      "qualifications.records.award",
      "qualifications.signoff.manage",
      "readiness.unit.view",
      "attendance.view",
    ],
  },
  {
    name: "unit-leadership",
    label: "Unit Leadership",
    description: "Unit-scoped leadership preset for roster, readiness, and attendance management.",
    permissionKeys: [
      ...memberPermissionKeys,
      "personnel.actions.view",
      "roster.member.edit",
      "roster.rank.change",
      "roster.position.assign",
      "roster.status.change",
      "units.positions.view",
      "units.positions.manage",
      "units.slots.manage",
      "unit.readiness.view",
      "units.readiness.view",
      "qualifications.matrix.view",
      "qualifications.requirements.view",
      "readiness.unit.view",
      "attendance.view",
      "attendance.record",
      "attendance.edit",
      "attendance.reports.view",
      "attendance.policies.manage",
      "transfers.view",
      "transfers.review",
      "loa.view",
      "loa.review",
      "campaigns.statistics.view",
      "forms.view",
      "forms.review",
      "forms.approve",
      "forms.deny",
      "forms.comment",
      "forms.assign_reviewer",
      "builder.view",
      "builder.forms.manage",
      "builder.workflows.manage",
    ],
  },
  {
    name: "s1-staff",
    label: "S1 Staff",
    description: "Personnel administration preset for profile and roster management.",
    permissionKeys: [
      "personnel.profile.view",
      "personnel.dashboard.view",
      "personnel.profile.create",
      "personnel.profile.edit",
      "personnel.profile.status_change",
      "personnel.profile.service_record.view",
      "personnel.profile.service_record.edit",
      "personnel.profile.notes.view",
      "personnel.profile.notes.create",
      "personnel.profile.notes.manage",
      "personnel.profile.logs.view",
      "personnel.timeline.view",
      "personnel.actions.view",
      "personnel.actions.manage",
      "roster.member.view",
      "roster.member.create",
      "roster.member.edit",
      "roster.rank.change",
      "roster.unit.assign",
      "roster.position.assign",
      "roster.status.change",
      "roster.transfer.approve",
      "roster.transfer.reject",
      "roster.bulk_update",
      "units.assignments.manage",
      "transfers.view",
      "transfers.submit",
      "transfers.review",
      "loa.view",
      "loa.submit",
      "loa.review",
      "readiness.member.view",
      "readiness.unit.view",
      "forms.view",
      "forms.create",
      "forms.edit",
      "forms.archive",
      "forms.review",
      "forms.approve",
      "forms.deny",
      "forms.comment",
      "forms.assign_reviewer",
      "audit.view",
    ],
  },
  {
    name: "s3-staff",
    label: "S3 Staff",
    description: "Operations-focused preset for planning, events, and deployment control.",
    permissionKeys: [
      "s3.dashboard.view",
      "s3.missions.view",
      "s3.missions.create",
      "s3.missions.edit",
      "s3.missions.review",
      "s3.missions.approve",
      "s3.missions.publish",
      "s3.conops.view",
      "s3.conops.create",
      "s3.conops.edit",
      "s3.conops.publish",
      "s3.aars.view",
      "s3.aars.submit",
      "s3.aars.review",
      "s3.zeus.assign",
      "events.view",
      "events.create",
      "events.edit",
      "events.publish",
      "operations.center.view",
      "operations.package.view",
      "operations.package.edit",
      "operations.package.review",
      "operations.package.approve",
      "operations.package.publish",
      "operations.planning.view",
      "operations.planning.edit",
      "operations.readiness.view",
      "operations.readiness.evaluate",
      "operations.health.view",
      "operations.health.manage",
      "recommendations.view",
      "recommendations.manage",
      "operations.recommendations.view",
      "operations.command.view",
      "operations.command.manage",
      "operations.dashboard.customize",
      "operations.release.view",
      "operations.release.publish",
      "operations.release.history",
      "operations.tasking.view",
      "operations.tasking.manage",
      "operations.resources.manage",
      "operations.zeus.assign",
      "patrols.view",
      "patrols.create",
      "patrols.lead",
      "patrols.complete",
      "patrols.participants.manage",
      "patrols.rsvp",
      "patrols.aar.submit",
      "patrols.aar.review",
      "patrols.archive",
      "aars.submit",
      "aars.review",
      "aars.attachments.manage",
      "communications.view",
      "communications.send",
      "communications.history.view",
      "announcements.view",
      "announcements.manage",
      "announcements.send",
      "campaigns.view",
      "campaigns.create",
      "campaigns.edit",
      "campaigns.publish",
      "deployments.create",
      "deployments.edit",
      "deployments.publish",
      "deployments.resources.view",
      "deployments.resources.upload",
      "deployments.resources.edit",
      "deployments.resources.delete",
      "deployments.progression.view",
      "deployments.progression.manage",
      "attendance.view",
      "attendance.reports.view",
      "forms.view",
      "forms.review",
      "forms.comment",
      "discord.patrols.create",
      "discord.patrols.manage",
    ],
  },
  {
    name: "discord-manager",
    label: "Discord Manager",
    description: "Discord integration preset for server, channel, and notification management.",
    permissionKeys: [
      "discord.view",
      "discord.manage",
      "discord.servers.manage",
      "discord.channels.manage",
      "discord.roles.manage",
      "discord.members.view",
      "discord.members.sync",
      "discord.identity.view",
      "discord.gateway.view",
      "discord.gateway.manage",
      "discord.gateway.health.view",
      "discord.gateway.events.view",
      "discord.gateway.events.retry",
      "discord.gateway.events.resolve",
      "discord.gateway.handlers.view",
      "discord.gateway.handlers.manage",
      "discord.gateway.metrics.view",
      "discord.gateway.voice.view",
      "discord.gateway.voice.manage",
      "discord.gateway.attachments.view",
      "discord.gateway.diagnostics.view",
      "discord.gateway.configuration.manage",
      "discord.events.view",
      "discord.events.manage",
      "discord.events.preview",
      "discord.events.publish",
      "discord.events.update",
      "discord.events.cancel",
      "discord.events.approve",
      "discord.events.retry",
      "discord.events.reconcile",
      "discord.events.templates.view",
      "discord.events.templates.manage",
      "discord.events.policies.view",
      "discord.events.policies.manage",
      "discord.events.participation.view",
      "discord.events.participation.manage",
      "discord.events.diagnostics.view",
      "discord.events.history.view",
      "discord.guilds.manage",
      "discord.guilds.discover",
      "discord.guilds.health.view",
      "discord.guilds.diagnostics.view",
      "discord.guilds.audit.view",
      "discord.discovery.view",
      "discord.discovery.run",
      "discord.discovery.cancel",
      "discord.resources.view",
      "discord.resources.manage",
      "discord.reconciliation.view",
      "discord.reconciliation.manage",
      "discord.sync.schedule.manage",
      "discord.mappings.manage",
      "discord.automation.view",
      "discord.automation.manage",
      "discord.automation.preview",
      "discord.automation.approve",
      "discord.automation.execute",
      "discord.automation.retry",
      "discord.automation.rollback",
      "discord.automation.exceptions.view",
      "discord.automation.exceptions.manage",
      "discord.automation.history.view",
      "discord.communications.view",
      "discord.communications.manage",
      "discord.applications.view",
      "discord.applications.manage",
      "discord.applications.catalog.view",
      "discord.applications.catalog.manage",
      "discord.applications.policies.view",
      "discord.applications.policies.manage",
      "discord.applications.panels.view",
      "discord.applications.panels.manage",
      "discord.applications.review.view",
      "discord.applications.review.assign",
      "discord.applications.review.request_information",
      "discord.applications.review.approve",
      "discord.applications.review.deny",
      "discord.applications.sessions.view",
      "discord.applications.sessions.manage",
      "discord.applications.diagnostics.view",
      "discord.applications.history.view",
      "discord.moderation.view",
      "discord.moderation.warn",
      "discord.moderation.timeout",
      "discord.moderation.kick",
      "discord.moderation.ban",
      "discord.moderation.appeals",
      "discord.moderation.policy.manage",
      "discord.moderation.case.manage",
      "discord.moderation.history.view",
      "communications.routing.view",
      "communications.routing.manage",
      "communications.delivery.view",
      "communications.health.view",
      "qualifications.discord_automation.view",
      "qualifications.discord_automation.manage",
      "personnel.discord_automation.view",
      "discord.notifications.send",
      "discord.sync.run",
      "discord.sync.view",
      "discord.bot.health.view",
      "discord.voice.view",
      "discord.voice.manage",
      "discord.roles.sync",
      "discord.nicknames.sync",
      "discord.diagnostics.view",
      "notifications.view",
      "notifications.send",
      "notifications.delivery.view",
      "builder.view",
    ],
  },
  {
    name: "community-manager",
    label: "Community Manager",
    description: "Community management preset for case review, incidents, appeals, notes, and moderation history.",
    permissionKeys: [
      "community.view",
      "community.manage",
      "community.dashboard.view",
      "cases.view",
      "cases.create",
      "cases.edit",
      "cases.assign",
      "cases.transition",
      "cases.close",
      "cases.reopen",
      "cases.archive",
      "cases.restricted.view",
      "cases.command.view",
      "evidence.view",
      "evidence.manage",
      "notes.view",
      "notes.manage",
      "incidents.view",
      "incidents.create",
      "incidents.manage",
      "appeals.view",
      "appeals.submit",
      "appeals.review",
      "moderation.view",
      "moderation.warn",
      "moderation.kick",
      "moderation.timeout",
      "moderation.ban",
      "moderation.reverse",
      "moderation.history.view",
      "discord.moderation.view",
      "discord.moderation.warn",
      "discord.moderation.timeout",
      "discord.moderation.kick",
      "discord.moderation.ban",
      "discord.moderation.appeals",
      "discord.moderation.policy.manage",
      "discord.moderation.case.manage",
      "discord.moderation.history.view",
      "communications.view",
      "communications.send",
      "notifications.delivery.view",
      "audit.view",
    ],
  },
  {
    name: "system-administrator",
    label: "System Administrator",
    description: "Full-system preset represented through explicit permission assignment.",
    grantsAllSystemPermissions: true,
  },
] as const;

export type SystemPermissionDefinition = (typeof systemPermissionCatalog)[number];
export type StarterRolePresetDefinition = (typeof starterRolePresets)[number];
