type CatalogEntry = {
  key: string;
  label: string;
  description: string;
};

type PermissionGroupDefinition = {
  module: string;
  category: string;
  permissions: CatalogEntry[];
};

type StarterRolePreset = {
  name: string;
  label: string;
  description: string;
  permissionKeys?: readonly string[];
  grantsAllSystemPermissions?: boolean;
};

export const profileStatusCatalog = [
  { key: "applicant", label: "Applicant", description: "Prospective member awaiting intake review." },
  { key: "recruit", label: "Recruit", description: "Member in initial onboarding or probationary status." },
  { key: "active", label: "Active", description: "Fully active member in good standing." },
  { key: "reserve", label: "Reserve", description: "Member available on a reserve or reduced-participation basis." },
  { key: "loa", label: "LOA", description: "Member currently on leave of absence." },
  { key: "inactive", label: "Inactive", description: "Member not actively participating but retained in records." },
  { key: "retired", label: "Retired", description: "Former member retained for historical reporting." },
  { key: "discharged", label: "Discharged", description: "Member removed from the unit structure." },
  { key: "banned", label: "Banned", description: "Member barred from community participation." },
] as const satisfies readonly CatalogEntry[];

export const spearheadUnitCatalog = [
  { key: "spearhead-command", name: "Spearhead Command", shortName: "Spearhead", parentKey: null, sortOrder: 10 },
  { key: "reaper", name: "3rd Infantry Division", shortName: "Reaper", parentKey: "spearhead-command", sortOrder: 20 },
  { key: "misfit", name: "75th Ranger Regiment", shortName: "Misfit", parentKey: "spearhead-command", sortOrder: 30 },
  { key: "gambler", name: "1st Air Cavalry Brigade", shortName: "Gambler", parentKey: "spearhead-command", sortOrder: 40 },
  { key: "viking", name: "Detachment-7", shortName: "Viking", parentKey: "spearhead-command", sortOrder: 50 },
] as const;

export const qualificationCategoryCatalog = [
  { key: "basic-infantry", label: "Basic Infantry", description: "Entry-level infantry readiness qualifications.", sortOrder: 10 },
  { key: "leadership", label: "Leadership", description: "Leadership-focused development and command qualifications.", sortOrder: 20 },
  { key: "medical", label: "Medical", description: "Medical treatment, triage, and combat lifesaver training.", sortOrder: 30 },
  { key: "communications", label: "Communications", description: "Radio procedure, signal, and comms workflow training.", sortOrder: 40 },
  { key: "aviation", label: "Aviation", description: "Flight, aircrew, and air support-related qualifications.", sortOrder: 50 },
  { key: "reconnaissance", label: "Reconnaissance", description: "Recon, surveillance, and scouting qualifications.", sortOrder: 60 },
  { key: "mission-maker", label: "Operation Planner", description: "Operation creation, scenario support, and operations prep qualifications.", sortOrder: 70 },
  { key: "zeus", label: "Zeus", description: "Game master and operational oversight qualifications.", sortOrder: 80 },
  { key: "staff", label: "Staff", description: "Staff workflow and command-support qualifications.", sortOrder: 90 },
  { key: "unit-specific", label: "Unit-Specific", description: "Qualifications defined by a specific unit or detachment.", sortOrder: 100 },
] as const;

export const documentCategoryCatalog = [
  { key: "general", label: "General", description: "General knowledge-base content and reference material.", sortOrder: 10 },
  { key: "sop", label: "SOP", description: "Standard operating procedures for repeatable unit workflows.", sortOrder: 20 },
  { key: "tacsop", label: "TACSOP", description: "Tactical SOP references for field and operation execution.", sortOrder: 30 },
  { key: "training", label: "Training", description: "Training guides, qualification prep, and instructional material.", sortOrder: 40 },
  { key: "administration", label: "Administration", description: "Administrative policy, forms, and internal guidance.", sortOrder: 50 },
  { key: "intel", label: "Intel", description: "Intelligence briefs, reference packs, and operation prep material.", sortOrder: 60 },
  { key: "operations", label: "Operations", description: "Operational planning and execution references.", sortOrder: 70 },
  { key: "conop", label: "CONOP", description: "Concept of operations and operation briefing content.", sortOrder: 80 },
  { key: "aar", label: "AAR", description: "After-action review material and historical operation documentation.", sortOrder: 90 },
  { key: "forms", label: "Forms", description: "Reusable forms, templates, and admin paperwork.", sortOrder: 100 },
  { key: "templates", label: "Templates", description: "Boilerplates for future operation, policy, and training documents.", sortOrder: 110 },
  { key: "public", label: "Public", description: "Member-facing public reference content.", sortOrder: 120 },
  { key: "restricted", label: "Restricted", description: "Restricted content that requires additional access controls.", sortOrder: 130 },
  { key: "unit-specific", label: "Unit-Specific", description: "Content owned by or scoped to a specific unit.", sortOrder: 140 },
] as const;

export const formTemplateTypeCatalog = [
  { key: "recruit_application", label: "Recruit Application", description: "Initial application intake for prospective members." },
  { key: "unit_transfer_request", label: "Unit Transfer Request", description: "Request reassignment between units or detachments." },
  { key: "loa_request", label: "LOA Request", description: "Request leave of absence or temporary inactive accommodation." },
  { key: "staff_application", label: "Staff Application", description: "Apply for a staff-facing support or command role." },
  { key: "instructor_application", label: "Instructor Application", description: "Apply for instructor or training cadre responsibilities." },
  { key: "rasp_application", label: "RASP Application", description: "Placeholder application type for future RASP workflow support." },
] as const satisfies readonly CatalogEntry[];

export const formFieldTypeCatalog = [
  { key: "short_text", label: "Short Text", description: "Single-line free-text response." },
  { key: "long_text", label: "Long Text", description: "Long-form paragraph response." },
  { key: "dropdown", label: "Dropdown", description: "Select a single option from a dropdown list." },
  { key: "checkbox", label: "Checkbox", description: "Confirm a boolean response." },
  { key: "radio", label: "Radio", description: "Choose one option from a small option set." },
  { key: "date", label: "Date", description: "Date-only field for scheduling or request timing." },
  { key: "discord_name", label: "Discord Name", description: "Portal-populated Discord display name or username reference." },
  { key: "steam_arma_id", label: "Steam / Arma ID", description: "Identifier field for Steam or Arma profile references." },
  { key: "unit_selector", label: "Unit Selector", description: "Select a target or preferred unit from known Spearhead units." },
  { key: "member_selector", label: "Member Selector", description: "Select a portal member profile for staff-facing workflows." },
  { key: "file_upload", label: "File Upload Placeholder", description: "Placeholder field reserved for future attachment support." },
  { key: "acknowledgement_checkbox", label: "Acknowledgement Checkbox", description: "Confirm acknowledgement of a policy, requirement, or statement." },
] as const satisfies readonly CatalogEntry[];

export const submissionStatusCatalog = [
  { key: "draft", label: "Draft", description: "Submission is being prepared and has not been formally routed.", sortOrder: 10, isDefault: true, isTerminal: false },
  { key: "submitted", label: "Submitted", description: "Submission was submitted and is waiting to enter review.", sortOrder: 20, isDefault: false, isTerminal: false },
  { key: "under_review", label: "Under Review", description: "Submission is actively being reviewed by assigned staff.", sortOrder: 30, isDefault: false, isTerminal: false },
  { key: "changes_requested", label: "Changes Requested", description: "Reviewer requested clarification or changes before approval.", sortOrder: 40, isDefault: false, isTerminal: false },
  { key: "approved", label: "Approved", description: "Submission was approved and is ready for downstream workflow follow-up.", sortOrder: 50, isDefault: false, isTerminal: true },
  { key: "denied", label: "Denied", description: "Submission was denied and closed.", sortOrder: 60, isDefault: false, isTerminal: true },
  { key: "withdrawn", label: "Withdrawn", description: "Submitter withdrew the request before final resolution.", sortOrder: 70, isDefault: false, isTerminal: true },
  { key: "archived", label: "Archived", description: "Submission is retained for history but removed from active queues.", sortOrder: 80, isDefault: false, isTerminal: true },
] as const;

export const rankCatalog = [
  { key: "pvt", label: "Private", abbreviation: "PVT", sortOrder: 10, isOfficer: false },
  { key: "pv2", label: "Private Second Class", abbreviation: "PV2", sortOrder: 20, isOfficer: false },
  { key: "pfc", label: "Private First Class", abbreviation: "PFC", sortOrder: 30, isOfficer: false },
  { key: "spc", label: "Specialist", abbreviation: "SPC", sortOrder: 40, isOfficer: false },
  { key: "cpl", label: "Corporal", abbreviation: "CPL", sortOrder: 50, isOfficer: false },
  { key: "sgt", label: "Sergeant", abbreviation: "SGT", sortOrder: 60, isOfficer: false },
  { key: "ssg", label: "Staff Sergeant", abbreviation: "SSG", sortOrder: 70, isOfficer: false },
  { key: "sfc", label: "Sergeant First Class", abbreviation: "SFC", sortOrder: 80, isOfficer: false },
  { key: "msg", label: "Master Sergeant", abbreviation: "MSG", sortOrder: 90, isOfficer: false },
  { key: "1sg", label: "First Sergeant", abbreviation: "1SG", sortOrder: 100, isOfficer: false },
  { key: "sgm", label: "Sergeant Major", abbreviation: "SGM", sortOrder: 110, isOfficer: false },
  { key: "csm", label: "Command Sergeant Major", abbreviation: "CSM", sortOrder: 120, isOfficer: false },
  { key: "2lt", label: "Second Lieutenant", abbreviation: "2LT", sortOrder: 130, isOfficer: true },
  { key: "1lt", label: "First Lieutenant", abbreviation: "1LT", sortOrder: 140, isOfficer: true },
  { key: "cpt", label: "Captain", abbreviation: "CPT", sortOrder: 150, isOfficer: true },
  { key: "maj", label: "Major", abbreviation: "MAJ", sortOrder: 160, isOfficer: true },
  { key: "ltc", label: "Lieutenant Colonel", abbreviation: "LTC", sortOrder: 170, isOfficer: true },
  { key: "col", label: "Colonel", abbreviation: "COL", sortOrder: 180, isOfficer: true },
] as const;

export const campaignStatusCatalog = [
  "planning",
  "preparing",
  "active",
  "completed",
  "archived",
] as const;

export const eventTypeCatalog = [
  {
    key: "operation",
    label: "Weekend Operation",
    description: "Primary weekend operation inside a deployment week.",
  },
  {
    key: "patrol",
    label: "Patrol",
    description: "Member-led patrol or weekday operation that normally requires a follow-up AAR.",
  },
  {
    key: "training",
    label: "Training",
    description: "Formal training, lane, or qualification event.",
  },
  {
    key: "meeting",
    label: "Meeting",
    description: "Leadership, staff, or unit meeting.",
  },
  {
    key: "community-event",
    label: "Community Event",
    description: "Community-wide or social event outside standard operations.",
  },
] as const satisfies readonly CatalogEntry[];

export const eventStatusCatalog = [
  {
    key: "draft",
    label: "Draft",
    description: "Created but not yet published to the portal audience.",
  },
  {
    key: "published",
    label: "Published",
    description: "Visible for RSVP and attendance planning.",
  },
  {
    key: "cancelled",
    label: "Cancelled",
    description: "Cancelled and no longer expected to occur.",
  },
  {
    key: "completed",
    label: "Completed",
    description: "Event occurred and attendance has been finalized.",
  },
  {
    key: "archived",
    label: "Archived",
    description: "Historical event retained for reporting and audit purposes.",
  },
] as const satisfies readonly CatalogEntry[];

export const patrolTypeCatalog = [
  { key: "recon", label: "Recon", description: "Reconnaissance patrol focused on intelligence gathering." },
  { key: "combat-patrol", label: "Combat Patrol", description: "Combat patrol expected to make or exploit contact." },
  { key: "logistics", label: "Logistics", description: "Logistics, resupply, or movement support patrol." },
  { key: "qrf", label: "QRF", description: "Quick reaction patrol or response posture." },
  { key: "training", label: "Training", description: "Lightweight patrol used for practice or familiarization." },
  { key: "intel", label: "Intel", description: "Patrol focused on intelligence validation or collection." },
  { key: "other", label: "Other", description: "Other lightweight patrol activity." },
] as const satisfies readonly CatalogEntry[];

export const patrolStatusCatalog = [
  { key: "planning", label: "Planning", description: "Patrol is being prepared but has not started." },
  { key: "running", label: "Running", description: "Patrol is active now." },
  { key: "completed", label: "Completed", description: "Patrol has ended and is ready for AAR follow-up." },
  { key: "awaiting-aar", label: "Awaiting AAR", description: "Patrol is complete and the required AAR has not been submitted." },
  { key: "aar-submitted", label: "AAR Submitted", description: "Patrol AAR text has been submitted." },
  { key: "reviewed", label: "Reviewed", description: "Patrol AAR has been reviewed by S3." },
  { key: "archived", label: "Archived", description: "Patrol is closed for active workflow purposes." },
] as const satisfies readonly CatalogEntry[];

export const deploymentResourceTypeCatalog = [
  { key: "CONOP", label: "CONOP", description: "Weekly operation CONOP file or external link." },
  { key: "OPORD", label: "OPORD", description: "Operation order link or uploaded PDF." },
  { key: "PLAYER_PRIMER", label: "Player Primer", description: "Member-facing primer or prep document." },
  { key: "ARMA3_PRESET", label: "Arma 3 Preset", description: "Arma 3 Launcher HTML preset file." },
  { key: "MAP", label: "AO Map", description: "Area of operations map or map pack." },
  { key: "INTELLIGENCE", label: "Intelligence", description: "Intel brief, imagery, or reference material." },
  { key: "RADIO_PLAN", label: "Radio Plan", description: "Radio plan, frequency card, or comms reference." },
  { key: "BRIEFING", label: "Briefing", description: "Briefing document or presentation." },
  { key: "MOD_COLLECTION", label: "Mod Collection", description: "Steam Workshop collection or mod list." },
  { key: "DOCUMENT", label: "Document", description: "General deployment document." },
  { key: "IMAGE", label: "Image", description: "Deployment image or visual reference." },
  { key: "VIDEO", label: "Video", description: "Video briefing or reference." },
  { key: "OTHER", label: "Other", description: "Other deployment resource." },
] as const satisfies readonly CatalogEntry[];

export const deploymentResourceVisibilityCatalog = [
  { key: "members", label: "Members", description: "Visible to members as the current active version." },
  { key: "staff", label: "Staff", description: "Visible to staff/admins only." },
  { key: "admin", label: "Admin", description: "Visible to admins only." },
] as const satisfies readonly CatalogEntry[];

export const missionStatusCatalog = [
  {
    key: "draft",
    label: "Draft",
    description: "Operation record is being prepared by the owner or staff.",
  },
  {
    key: "s3-review",
    label: "S3 Review",
    description: "Operation is waiting for S3 review and approval.",
  },
  {
    key: "approved",
    label: "Approved",
    description: "Operation has been approved but is not yet published to the wider portal audience.",
  },
  {
    key: "published",
    label: "Published",
    description: "Operation is approved and published for member-facing visibility.",
  },
  {
    key: "completed",
    label: "Completed",
    description: "Operation occurred and is awaiting or supporting post-operation review.",
  },
  {
    key: "aar-submitted",
    label: "AAR Submitted",
    description: "An after-action review has been submitted for the operation or patrol.",
  },
  {
    key: "archived",
    label: "Archived",
    description: "Operation lifecycle is closed and retained for historical reporting.",
  },
] as const satisfies readonly CatalogEntry[];

export const conopStatusCatalog = [
  {
    key: "draft",
    label: "Draft",
    description: "CONOP is being drafted and reviewed internally.",
  },
  {
    key: "published",
    label: "Published",
    description: "CONOP is ready for operational reference.",
  },
] as const satisfies readonly CatalogEntry[];

export const aarStatusCatalog = [
  {
    key: "draft",
    label: "Draft",
    description: "AAR is being prepared and has not been submitted for review.",
  },
  {
    key: "submitted",
    label: "Submitted",
    description: "AAR has been submitted for S3 review.",
  },
  {
    key: "pending-map",
    label: "Pending Map Screenshot",
    description: "Patrol AAR report exists but is missing the required map screenshot.",
  },
  {
    key: "reviewed",
    label: "Reviewed",
    description: "AAR has been reviewed and finalized by staff.",
  },
] as const satisfies readonly CatalogEntry[];

export const attendanceStatusCatalog = {
  rsvp: ["yes", "no", "maybe"] as const,
  final: ["present", "absent", "excused", "late", "loa"] as const,
};

const permissionGroups = [
  {
    module: "core",
    category: "general",
    permissions: [
      { key: "core.dashboard.view", label: "View dashboard", description: "Access the main dashboard and summary widgets." },
      { key: "core.search.use", label: "Use global search", description: "Use command palette and search-first navigation tools." },
      { key: "core.notifications.view", label: "View notifications", description: "View notification center activity and delivery summaries." },
    ],
  },
  {
    module: "personnel",
    category: "profiles",
    permissions: [
      { key: "personnel.profile.view", label: "View profiles", description: "Open and inspect member profile records." },
      { key: "personnel.profile.create", label: "Create profiles", description: "Create new member profile records." },
      { key: "personnel.profile.edit", label: "Edit profiles", description: "Edit core member profile details." },
      { key: "personnel.profile.archive", label: "Archive profiles", description: "Archive or retire member profile records." },
      { key: "personnel.profile.status_change", label: "Change profile status", description: "Change a member profile status classification." },
      { key: "personnel.profile.service_record.view", label: "View service records", description: "View service record history and official personnel data." },
      { key: "personnel.profile.service_record.edit", label: "Edit service records", description: "Edit service record and personnel history details." },
      { key: "personnel.profile.notes.view", label: "View profile notes", description: "View permission-restricted profile notes." },
      { key: "personnel.profile.notes.create", label: "Create profile notes", description: "Create permission-restricted profile notes." },
      { key: "personnel.profile.notes.edit", label: "Edit profile notes", description: "Edit existing profile notes." },
      { key: "personnel.profile.notes.delete", label: "Delete profile notes", description: "Delete profile notes when permitted by policy." },
      { key: "personnel.profile.logs.view", label: "View profile logs", description: "Review profile-level logs and history entries." },
    ],
  },
  {
    module: "roster",
    category: "assignments",
    permissions: [
      { key: "roster.member.view", label: "View roster", description: "View roster assignments and unit placement data." },
      { key: "roster.member.create", label: "Create roster entries", description: "Create roster entries or assignments for members." },
      { key: "roster.member.edit", label: "Edit roster entries", description: "Edit current roster assignments and member placement." },
      { key: "roster.member.archive", label: "Archive roster entries", description: "Archive roster entries that should no longer be active." },
      { key: "roster.rank.change", label: "Change rank", description: "Change a member's current rank." },
      { key: "roster.unit.assign", label: "Assign unit", description: "Assign or transfer a member to a unit." },
      { key: "roster.position.assign", label: "Assign position", description: "Assign or reassign a member to a position." },
      { key: "roster.status.change", label: "Change roster status", description: "Change roster and readiness status indicators." },
      { key: "roster.transfer.request", label: "Request transfer", description: "Request a roster transfer between units or assignments." },
      { key: "roster.transfer.approve", label: "Approve transfer", description: "Approve a pending roster transfer." },
      { key: "roster.transfer.reject", label: "Reject transfer", description: "Reject a pending roster transfer." },
      { key: "roster.bulk_update", label: "Bulk update roster", description: "Perform bulk roster updates for administrative workflows." },
    ],
  },
  {
    module: "units",
    category: "structure",
    permissions: [
      { key: "units.view", label: "View units", description: "View unit hierarchy and roster overview information." },
      { key: "units.create", label: "Create units", description: "Create units within the command hierarchy." },
      { key: "units.edit", label: "Edit units", description: "Edit unit metadata and organization details." },
      { key: "units.archive", label: "Archive units", description: "Archive or deactivate units." },
      { key: "units.hierarchy.manage", label: "Manage unit hierarchy", description: "Manage parent and child unit relationships." },
      { key: "units.positions.view", label: "View positions", description: "View unit positions and billet definitions." },
      { key: "units.positions.create", label: "Create positions", description: "Create new unit positions or billets." },
      { key: "units.positions.edit", label: "Edit positions", description: "Edit unit position definitions." },
      { key: "units.positions.archive", label: "Archive positions", description: "Archive no-longer-used positions." },
      { key: "units.slots.view", label: "View unit slots", description: "View unit slot and billet availability." },
      { key: "units.slots.manage", label: "Manage unit slots", description: "Manage slot occupancy and billet readiness." },
      { key: "units.dashboard.view", label: "View unit dashboards", description: "Access unit-specific dashboard views." },
      { key: "unit.readiness.view", label: "View unit readiness", description: "View unit-scoped readiness, attendance, and qualification signals." },
      { key: "unit.requirements.manage", label: "Manage unit requirements", description: "Manage unit-specific readiness and qualification requirement timelines." },
    ],
  },
  {
    module: "qualifications",
    category: "readiness",
    permissions: [
      { key: "qualifications.view", label: "View qualifications", description: "View qualification catalog and summary details." },
      { key: "qualifications.create", label: "Create qualifications", description: "Create qualification catalog entries." },
      { key: "qualifications.edit", label: "Edit qualifications", description: "Edit qualification definitions and metadata." },
      { key: "qualifications.archive", label: "Archive qualifications", description: "Archive qualification definitions." },
      { key: "qualifications.categories.manage", label: "Manage qualification categories", description: "Manage qualification category groupings." },
      { key: "qualifications.record.view", label: "View qualification records", description: "View qualification records awarded to members." },
      { key: "qualifications.record.award", label: "Award qualifications", description: "Award qualifications to members." },
      { key: "qualifications.record.revoke", label: "Revoke qualifications", description: "Revoke or invalidate member qualifications." },
      { key: "qualifications.record.edit", label: "Edit qualification records", description: "Edit awarded qualification records." },
      { key: "qualifications.matrix.view", label: "View qualification matrix", description: "View readiness matrix across members and units." },
      { key: "qualifications.requirements.view", label: "View qualification requirements", description: "View unit and position qualification requirements." },
      { key: "qualifications.requirements.manage", label: "Manage qualification requirements", description: "Manage unit and position qualification requirements." },
      { key: "qualifications.signoff.manage", label: "Manage qualification signoff", description: "Manage instructor signoff and certification workflows." },
    ],
  },
  {
    module: "forms",
    category: "workflow",
    permissions: [
      { key: "forms.view", label: "View forms", description: "View application templates and submission summaries." },
      { key: "forms.create", label: "Create forms", description: "Create application and request form templates." },
      { key: "forms.edit", label: "Edit forms", description: "Edit form templates, fields, and workflow metadata." },
      { key: "forms.archive", label: "Archive forms", description: "Archive or disable form templates." },
      { key: "forms.submit", label: "Submit forms", description: "Create and submit member-facing applications or requests." },
      { key: "forms.review", label: "Review submissions", description: "View and work staff review queues for form submissions." },
      { key: "forms.approve", label: "Approve submissions", description: "Approve form submissions and advance workflow state." },
      { key: "forms.deny", label: "Deny submissions", description: "Deny or reject form submissions." },
      { key: "forms.comment", label: "Comment on submissions", description: "Comment on form submissions and review threads." },
      { key: "forms.assign_reviewer", label: "Assign reviewers", description: "Assign or change reviewers for workflow submissions." },
      { key: "forms.admin", label: "Administer forms", description: "Full administrative access across templates, submissions, and workflow settings." },
    ],
  },
  {
    module: "events",
    category: "operations",
    permissions: [
      { key: "events.view", label: "View events", description: "View operations and training events." },
      { key: "events.create", label: "Create events", description: "Create event records." },
      { key: "events.edit", label: "Edit events", description: "Edit event scheduling and metadata." },
      { key: "events.delete", label: "Delete events", description: "Delete or remove events from the calendar." },
      { key: "events.publish", label: "Publish events", description: "Publish events to members and downstream clients." },
      { key: "events.cancel", label: "Cancel events", description: "Cancel scheduled events." },
      { key: "events.archive", label: "Archive events", description: "Archive past or retired events." },
      { key: "events.calendar.view", label: "View event calendar", description: "View calendar-oriented event scheduling surfaces." },
      { key: "operations.package.view", label: "View operations packages", description: "View planning packages for deployment weeks." },
      { key: "operations.package.edit", label: "Edit operations packages", description: "Prepare and maintain planning packages for deployment weeks." },
      { key: "operations.package.review", label: "Review operations packages", description: "Review Operations Package readiness and package validation state." },
      { key: "operations.package.approve", label: "Approve operations packages", description: "Approve Operations Packages for release workflows." },
      { key: "operations.package.publish", label: "Publish operations packages", description: "Publish Operations Packages when publishing workflows are enabled." },
      { key: "operations.planning.view", label: "View operations planning", description: "View S3 planning notes and operational-week context." },
      { key: "operations.planning.edit", label: "Edit operations planning", description: "Edit S3 planning notes and operational-week context." },
      { key: "operations.readiness.view", label: "View operations readiness", description: "View Operations Package readiness scores and validation issues." },
      { key: "operations.readiness.evaluate", label: "Evaluate operations readiness", description: "Run Operations Package readiness checks." },
      { key: "operations.release.view", label: "View operations releases", description: "View published Operations Release records." },
      { key: "operations.release.publish", label: "Publish operations releases", description: "Publish Operations Releases to configured delivery channels." },
      { key: "operations.release.history", label: "View operations release history", description: "View Operations Release history and amendment records." },
      { key: "operations.tasking.view", label: "View weekly tasking", description: "View operation-linked weekly tasking and unit tasking." },
      { key: "operations.tasking.manage", label: "Manage weekly tasking", description: "Create and edit weekly operation tasking." },
      { key: "operations.resources.manage", label: "Manage operations resources", description: "Attach and manage planning resources for operational weeks." },
      { key: "operations.zeus.assign", label: "Assign operations Zeus", description: "Assign or change Zeus ownership for operational planning." },
      { key: "operations.center.view", label: "View Operations Center", description: "View the Operations Center dashboard and command queues." },
      { key: "patrols.view", label: "View patrols", description: "View lightweight patrol records, participants, and AAR state." },
      { key: "patrols.create", label: "Start patrols", description: "Start lightweight patrol events through the portal operation workflow." },
      { key: "patrols.lead", label: "Lead patrols", description: "Be assigned as or act as a patrol leader for portal patrol events." },
      { key: "patrols.complete", label: "Complete patrols", description: "Mark a running patrol complete and move it into AAR follow-up." },
      { key: "patrols.participants.manage", label: "Manage patrol participants", description: "Manually add or remove confirmed patrol participants." },
      { key: "patrols.rsvp", label: "RSVP to patrols", description: "Record lightweight patrol interest without marking final attendance." },
      { key: "patrols.aar.submit", label: "Submit patrol AARs", description: "Submit required Patrol AAR reports and screenshots." },
      { key: "patrols.aar.review", label: "Review patrol AARs", description: "Review Patrol AARs and progression recommendations." },
      { key: "patrols.archive", label: "Archive patrols", description: "Archive patrol records after review." },
      { key: "aars.submit", label: "Submit AARs", description: "Submit patrol after-action reviews." },
      { key: "aars.review", label: "Review AARs", description: "Review submitted after-action reviews." },
      { key: "aars.attachments.manage", label: "Manage AAR attachments", description: "Upload and manage Patrol AAR screenshots and supporting media." },
    ],
  },
  {
    module: "attendance",
    category: "tracking",
    permissions: [
      { key: "attendance.view", label: "View attendance", description: "View attendance and RSVP records." },
      { key: "attendance.rsvp.view", label: "View RSVP state", description: "View RSVP status for events." },
      { key: "attendance.rsvp.manage", label: "Manage RSVP state", description: "Manage RSVP state on behalf of members." },
      { key: "attendance.record", label: "Record attendance", description: "Record final attendance results." },
      { key: "attendance.edit", label: "Edit attendance", description: "Edit attendance records after initial entry." },
      { key: "attendance.override", label: "Override attendance", description: "Override attendance results for sensitive corrections." },
      { key: "attendance.lock", label: "Lock attendance", description: "Lock attendance records after closeout." },
      { key: "attendance.reports.view", label: "View attendance reports", description: "View attendance reporting and trend surfaces." },
    ],
  },
  {
    module: "campaigns",
    category: "operations",
    permissions: [
      { key: "campaigns.view", label: "View deployments", description: "View deployment summaries and detail pages." },
      { key: "campaigns.create", label: "Create deployments", description: "Create deployments and planning records." },
      { key: "campaigns.edit", label: "Edit deployments", description: "Edit deployment metadata and narrative details." },
      { key: "campaigns.publish", label: "Publish deployments", description: "Publish deployment updates." },
      { key: "campaigns.archive", label: "Archive deployments", description: "Archive completed or retired deployments." },
      { key: "campaigns.timeline.manage", label: "Manage deployment timeline", description: "Manage deployment timeline entries and operation type/phase tracking." },
      { key: "campaigns.statistics.view", label: "View deployment statistics", description: "View deployment participation and readiness statistics." },
      { key: "campaigns.documents.manage", label: "Manage deployment documents", description: "Manage deployment-related planning and archival documents." },
      { key: "deployments.create", label: "Create deployments", description: "Create configurable multi-week deployment records." },
      { key: "deployments.edit", label: "Edit deployments", description: "Edit deployment metadata, duration, and Zeus assignment." },
      { key: "deployments.publish", label: "Publish deployments", description: "Publish deployment records and related operation visibility." },
      { key: "deployments.resources.view", label: "View deployment resources", description: "View current deployment resource files and links." },
      { key: "deployments.resources.upload", label: "Upload deployment resources", description: "Upload deployment resource files and replacement versions." },
      { key: "deployments.resources.edit", label: "Edit deployment resources", description: "Edit deployment resource metadata and current version." },
      { key: "deployments.resources.delete", label: "Archive deployment resources", description: "Archive deployment resources and old versions." },
      { key: "deployments.progression.view", label: "View deployment progression", description: "View AAR-informed deployment progression recommendations and planning notes." },
      { key: "deployments.progression.manage", label: "Manage deployment progression", description: "Record progression decisions, next-operation recommendations, and planning notes." },
    ],
  },
  {
    module: "s3",
    category: "staff-operations",
    permissions: [
      { key: "s3.dashboard.view", label: "View S3 dashboard", description: "Access the S3 oversight dashboard." },
      { key: "s3.missions.view", label: "View operations", description: "View S3 operation planning records." },
      { key: "s3.missions.create", label: "Create operations", description: "Create draft operation planning records." },
      { key: "s3.missions.edit", label: "Edit operations", description: "Edit operation planning records." },
      { key: "s3.missions.review", label: "Review operations", description: "Review pending operation planning work." },
      { key: "s3.missions.approve", label: "Approve operations", description: "Approve operation planning work." },
      { key: "s3.missions.reject", label: "Reject operations", description: "Reject or return operation planning work." },
      { key: "s3.missions.publish", label: "Publish operations", description: "Publish approved operations." },
      { key: "s3.missions.archive", label: "Archive operations", description: "Archive older or superseded operation records." },
      { key: "s3.conops.view", label: "View CONOPs", description: "View concept-of-operations content." },
      { key: "s3.conops.create", label: "Create CONOPs", description: "Create concept-of-operations records." },
      { key: "s3.conops.edit", label: "Edit CONOPs", description: "Edit concept-of-operations records." },
      { key: "s3.conops.publish", label: "Publish CONOPs", description: "Publish concept-of-operations records." },
      { key: "s3.aars.view", label: "View AARs", description: "View after-action review content." },
      { key: "s3.aars.submit", label: "Submit AARs", description: "Submit after-action review records." },
      { key: "s3.aars.review", label: "Review AARs", description: "Review after-action review submissions." },
      { key: "s3.zeus.assign", label: "Assign Zeus", description: "Assign or change deployment and operation Zeus ownership." },
    ],
  },
  {
    module: "documents",
    category: "content",
    permissions: [
      { key: "documents.view", label: "View documents", description: "View documents and guides." },
      { key: "documents.create", label: "Create documents", description: "Create managed document records." },
      { key: "documents.edit", label: "Edit documents", description: "Edit managed document records." },
      { key: "documents.delete", label: "Delete documents", description: "Delete document records when policy permits removal." },
      { key: "documents.archive", label: "Archive documents", description: "Archive or retire documents." },
      { key: "documents.publish", label: "Publish documents", description: "Publish documents to the portal." },
      { key: "documents.restrict", label: "Restrict documents", description: "Restrict document access or visibility." },
      { key: "documents.attachments.manage", label: "Manage document attachments", description: "Add, remove, and manage document attachments." },
      { key: "documents.categories.manage", label: "Manage document categories", description: "Manage document categories and organization." },
      { key: "documents.review.manage", label: "Manage document reviews", description: "Manage review dates and document review workflows." },
      { key: "documents.readreceipts.view", label: "View document read receipts", description: "View document acknowledgement and read-receipt records." },
      { key: "documents.permissions.manage", label: "Manage document permissions", description: "Manage document-specific access rules and permission rows." },
    ],
  },
  {
    module: "notifications",
    category: "delivery",
    permissions: [
      { key: "notifications.view", label: "View notifications", description: "View notification records and summaries." },
      { key: "notifications.send", label: "Send notifications", description: "Send manual or automated notifications." },
      { key: "notifications.templates.manage", label: "Manage notification templates", description: "Manage reusable notification templates." },
      { key: "notifications.delivery.view", label: "View notification delivery", description: "View notification delivery results." },
      { key: "notifications.delivery.retry", label: "Retry notification delivery", description: "Retry failed notification deliveries." },
    ],
  },
  {
    module: "discord",
    category: "integration",
    permissions: [
      { key: "discord.view", label: "View Discord settings", description: "View Discord integration settings and health." },
      { key: "discord.manage", label: "Manage Discord settings", description: "Manage Discord integration settings." },
      { key: "discord.servers.manage", label: "Manage Discord servers", description: "Manage Discord server mappings." },
      { key: "discord.channels.manage", label: "Manage Discord channels", description: "Manage Discord channel mappings." },
      { key: "discord.roles.manage", label: "Manage Discord roles", description: "Manage Discord role mappings." },
      { key: "discord.members.view", label: "View Discord members", description: "View linked Discord member state and sync status." },
      { key: "discord.members.sync", label: "Sync Discord members", description: "Run Discord guild member import and drift-correction sync." },
      { key: "discord.identity.view", label: "View Discord identities", description: "View Discord identity diagnostics, duplicate warnings, and OAuth/import link health." },
      { key: "discord.identity.merge", label: "Merge Discord identities", description: "Merge exact Discord ID duplicate portal identities without authorizing by role names." },
      { key: "discord.notifications.send", label: "Send Discord notifications", description: "Send portal notifications to Discord destinations." },
      { key: "discord.patrols.create", label: "Start Discord patrols", description: "Start portal Patrols from Discord commands." },
      { key: "discord.patrols.manage", label: "Manage Discord patrols", description: "Complete patrols and manage patrol workflows from Discord commands." },
      { key: "discord.sync.run", label: "Run Discord sync", description: "Run Discord synchronization jobs." },
      { key: "discord.sync.view", label: "View Discord sync", description: "View Discord synchronization state and history." },
      { key: "discord.moderation.kick", label: "Kick Discord members", description: "Kick mapped Discord members with required reason and audit logging." },
      { key: "discord.moderation.ban", label: "Ban Discord members", description: "Ban mapped Discord members when moderation policy allows it." },
      { key: "discord.moderation.timeout", label: "Timeout Discord members", description: "Apply or remove Discord member timeout when moderation policy allows it." },
      { key: "discord.moderation.history.view", label: "View Discord moderation history", description: "View Discord moderation action history." },
      { key: "discord.bot.health.view", label: "View Discord bot health", description: "View Discord bot health and status information." },
      { key: "admin.discord.manage", label: "Manage Discord administration", description: "Manage Discord administration surfaces and operator workflows." },
    ],
  },
  {
    module: "builder",
    category: "platform-builder",
    permissions: [
      { key: "builder.view", label: "View builder tools", description: "View platform builder tools and configuration surfaces." },
      { key: "builder.forms.manage", label: "Manage builder forms", description: "Manage form builder templates and fields." },
      { key: "builder.workflows.manage", label: "Manage workflow templates", description: "Manage workflow template foundations and approval routing." },
      { key: "builder.dashboards.manage", label: "Manage dashboard layouts", description: "Manage configurable dashboard layout foundations." },
      { key: "builder.widgets.manage", label: "Manage widget catalog", description: "Manage dashboard widget catalog visibility and configuration." },
      { key: "builder.automations.manage", label: "Manage automation rules", description: "Manage safe automation rule foundations and placeholders." },
    ],
  },
  {
    module: "admin",
    category: "administration",
    permissions: [
      { key: "admin.dashboard.view", label: "View admin dashboard", description: "View administration dashboard surfaces." },
      { key: "admin.users.view", label: "View users", description: "View portal user records." },
      { key: "admin.users.manage", label: "Manage users", description: "Manage portal users and profile linking." },
      { key: "admin.roles.view", label: "View roles", description: "View role and permission assignments." },
      { key: "admin.roles.create", label: "Create roles", description: "Create roles for the access model." },
      { key: "admin.roles.edit", label: "Edit roles", description: "Edit role metadata and membership." },
      { key: "admin.roles.delete", label: "Delete roles", description: "Delete or retire roles." },
      { key: "admin.permissions.view", label: "View permissions", description: "View the system-defined permission catalog." },
      { key: "admin.permissions.assign", label: "Assign permissions", description: "Assign permissions to roles." },
      { key: "admin.settings.view", label: "View system settings", description: "View system settings and configuration." },
      { key: "admin.settings.manage", label: "Manage system settings", description: "Manage system settings and configuration." },
    ],
  },
  {
    module: "audit",
    category: "compliance",
    permissions: [
      { key: "audit.view", label: "View audit logs", description: "View audit log entries and historical change records." },
      { key: "audit.export", label: "Export audit logs", description: "Export audit logs for compliance or reporting." },
    ],
  },
] as const satisfies readonly PermissionGroupDefinition[];

export const systemPermissionCatalog = permissionGroups.flatMap((group) =>
  group.permissions.map((permission) => ({
    ...permission,
    module: group.module,
    category: group.category,
    isSystem: true,
  })),
);

const memberPermissionKeys = [
  "core.dashboard.view",
  "core.search.use",
  "core.notifications.view",
  "personnel.profile.view",
  "personnel.profile.service_record.view",
  "roster.member.view",
  "units.view",
  "units.dashboard.view",
  "qualifications.view",
  "qualifications.record.view",
  "events.view",
  "events.calendar.view",
  "attendance.rsvp.view",
  "patrols.view",
  "patrols.create",
  "patrols.lead",
  "patrols.rsvp",
  "patrols.aar.submit",
  "aars.submit",
  "campaigns.view",
  "deployments.resources.view",
  "documents.view",
  "forms.view",
  "forms.submit",
  "forms.comment",
] as const;

export const starterRolePresets: readonly StarterRolePreset[] = [
  {
    name: "member",
    label: "Member",
    description: "Baseline self-service access for ordinary members.",
    permissionKeys: memberPermissionKeys,
  },
  {
    name: "instructor",
    label: "Instructor",
    description: "Qualification-focused preset for trainers and signoff authorities.",
    permissionKeys: [
      ...memberPermissionKeys,
      "qualifications.record.award",
      "qualifications.record.edit",
      "qualifications.signoff.manage",
      "attendance.view",
    ],
  },
  {
    name: "unit-leadership",
    label: "Unit Leadership",
    description: "Unit-scoped leadership preset for roster, readiness, and attendance management.",
    permissionKeys: [
      ...memberPermissionKeys,
      "roster.member.edit",
      "roster.rank.change",
      "roster.position.assign",
      "roster.status.change",
      "units.positions.view",
      "units.slots.manage",
      "unit.readiness.view",
      "qualifications.matrix.view",
      "qualifications.requirements.view",
      "attendance.view",
      "attendance.record",
      "attendance.edit",
      "attendance.reports.view",
      "campaigns.statistics.view",
      "forms.view",
      "forms.review",
      "forms.approve",
      "forms.deny",
      "forms.comment",
      "forms.assign_reviewer",
      "builder.view",
      "builder.forms.manage",
      "builder.workflows.manage",
    ],
  },
  {
    name: "s1-staff",
    label: "S1 Staff",
    description: "Personnel administration preset for profile and roster management.",
    permissionKeys: [
      "personnel.profile.view",
      "personnel.profile.create",
      "personnel.profile.edit",
      "personnel.profile.status_change",
      "personnel.profile.service_record.view",
      "personnel.profile.service_record.edit",
      "personnel.profile.notes.view",
      "personnel.profile.notes.create",
      "personnel.profile.logs.view",
      "roster.member.view",
      "roster.member.create",
      "roster.member.edit",
      "roster.rank.change",
      "roster.unit.assign",
      "roster.position.assign",
      "roster.status.change",
      "roster.transfer.approve",
      "roster.transfer.reject",
      "roster.bulk_update",
      "forms.view",
      "forms.create",
      "forms.edit",
      "forms.archive",
      "forms.review",
      "forms.approve",
      "forms.deny",
      "forms.comment",
      "forms.assign_reviewer",
      "audit.view",
    ],
  },
  {
    name: "s3-staff",
    label: "S3 Staff",
    description: "Operations-focused preset for planning, events, and deployment control.",
    permissionKeys: [
      "s3.dashboard.view",
      "s3.missions.view",
      "s3.missions.create",
      "s3.missions.edit",
      "s3.missions.review",
      "s3.missions.approve",
      "s3.missions.publish",
      "s3.conops.view",
      "s3.conops.create",
      "s3.conops.edit",
      "s3.conops.publish",
      "s3.aars.view",
      "s3.aars.submit",
      "s3.aars.review",
      "s3.zeus.assign",
      "events.view",
      "events.create",
      "events.edit",
      "events.publish",
      "operations.center.view",
      "operations.package.view",
      "operations.package.edit",
      "operations.package.review",
      "operations.package.approve",
      "operations.package.publish",
      "operations.planning.view",
      "operations.planning.edit",
      "operations.readiness.view",
      "operations.readiness.evaluate",
      "operations.release.view",
      "operations.release.publish",
      "operations.release.history",
      "operations.tasking.view",
      "operations.tasking.manage",
      "operations.resources.manage",
      "operations.zeus.assign",
      "patrols.view",
      "patrols.create",
      "patrols.lead",
      "patrols.complete",
      "patrols.participants.manage",
      "patrols.rsvp",
      "patrols.aar.submit",
      "patrols.aar.review",
      "patrols.archive",
      "aars.submit",
      "aars.review",
      "aars.attachments.manage",
      "campaigns.view",
      "campaigns.create",
      "campaigns.edit",
      "campaigns.publish",
      "deployments.create",
      "deployments.edit",
      "deployments.publish",
      "deployments.resources.view",
      "deployments.resources.upload",
      "deployments.resources.edit",
      "deployments.resources.delete",
      "deployments.progression.view",
      "deployments.progression.manage",
      "attendance.view",
      "attendance.reports.view",
      "forms.view",
      "forms.review",
      "forms.comment",
      "discord.patrols.create",
      "discord.patrols.manage",
    ],
  },
  {
    name: "discord-manager",
    label: "Discord Manager",
    description: "Discord integration preset for server, channel, and notification management.",
    permissionKeys: [
      "discord.view",
      "discord.manage",
      "discord.servers.manage",
      "discord.channels.manage",
      "discord.roles.manage",
      "discord.members.view",
      "discord.members.sync",
      "discord.identity.view",
      "discord.notifications.send",
      "discord.sync.run",
      "discord.sync.view",
      "discord.bot.health.view",
      "notifications.view",
      "notifications.send",
      "notifications.delivery.view",
      "builder.view",
    ],
  },
  {
    name: "system-administrator",
    label: "System Administrator",
    description: "Full-system preset represented through explicit permission assignment.",
    grantsAllSystemPermissions: true,
  },
] as const;

export type SystemPermissionDefinition = (typeof systemPermissionCatalog)[number];
export type StarterRolePresetDefinition = (typeof starterRolePresets)[number];
