import type { PersonaDashboardProfile, PersonaId, PersonaProfile, WorkspaceId } from "@/server/personas/types";

export const personaProfiles: Record<PersonaId, PersonaProfile> = {
  community_member: {
    defaultRoute: "/dashboard",
    description: "Personal portal for operations, unit tasking, notifications, qualifications, and member actions.",
    id: "community_member",
    label: "My Portal",
    priority: 10,
    reason: "Every authenticated portal user starts with a personal member workspace.",
    workspaceId: "my_portal",
  },
  patrol_leader: {
    defaultRoute: "/operations/patrols",
    description: "Patrol execution, participant management, completion, and required AAR follow-up.",
    id: "patrol_leader",
    label: "Patrol Leader",
    priority: 40,
    reason: "User can lead, complete, or submit Patrol/AAR workflow actions.",
    workspaceId: "patrol_leader",
  },
  unit_leadership: {
    defaultRoute: "/units",
    description: "Unit strength, readiness, assignments, qualifications, attendance, and current tasking.",
    id: "unit_leadership",
    label: "Unit Leadership",
    priority: 45,
    reason: "User has unit dashboard, roster, or unit-scoped leadership permissions.",
    workspaceId: "unit_leadership",
  },
  s1_personnel: {
    defaultRoute: "/personnel",
    description: "Personnel administration, profiles, roster movement, transfers, LOA, and identity repair.",
    id: "s1_personnel",
    label: "Personnel",
    priority: 50,
    reason: "User can view or manage personnel profiles, roster records, or personnel queues.",
    workspaceId: "personnel",
  },
  s3_operations: {
    defaultRoute: "/operations",
    description: "Current deployment, operations package, readiness, publication, patrols, and AAR review.",
    id: "s3_operations",
    label: "Operations",
    priority: 70,
    reason: "User has S3, operations package, release, patrol, or event operations permissions.",
    workspaceId: "operations",
  },
  deployment_creator: {
    defaultRoute: "/operations/deployments",
    description: "Deployment setup, resources, progression decisions, releases, and next-week planning.",
    id: "deployment_creator",
    label: "Deployment Creator",
    priority: 65,
    reason: "User can create, edit, or manage deployment progression.",
    workspaceId: "deployment_creator",
  },
  zeus: {
    defaultRoute: "/operations/zeus",
    description: "Assigned operation preparation, CONOP, OPORD, mod preset, tasking, and execution resources.",
    id: "zeus",
    label: "Zeus",
    priority: 55,
    reason: "User can view or assign Zeus operational ownership.",
    workspaceId: "zeus",
  },
  training_staff: {
    defaultRoute: "/training/qualification-matrix",
    description: "Qualification matrix, signoffs, requirements, expiring qualifications, and training readiness.",
    id: "training_staff",
    label: "Training",
    priority: 50,
    reason: "User has qualification record, matrix, requirement, or signoff permissions.",
    workspaceId: "training",
  },
  command_staff: {
    defaultRoute: "/dashboard",
    description: "Cross-domain risk, operational health, recommendations, readiness, cases, and decisions.",
    id: "command_staff",
    label: "Command",
    priority: 80,
    reason: "User can view command dashboards, recommendations, audit, or multiple command-level domains.",
    workspaceId: "command",
  },
  community_manager: {
    defaultRoute: "/community-management",
    description: "Critical cases, appeals, incident reports, moderation history, and community workload.",
    id: "community_manager",
    label: "Community",
    priority: 55,
    reason: "User can access Community Management or communications workflows.",
    workspaceId: "community",
  },
  administrator: {
    defaultRoute: "/administration",
    description: "Users, roles, permissions, Discord identity, delivery failures, audit, and system health.",
    id: "administrator",
    label: "Administration",
    priority: 90,
    reason: "User has administration, role, Discord, notification delivery, or audit permissions.",
    workspaceId: "administration",
  },
  developer: {
    defaultRoute: "/administration/builder",
    description: "Builder tools, diagnostics, registries, settings, and development-only controls.",
    id: "developer",
    label: "Developer",
    priority: 100,
    reason: "User has explicit builder or developer diagnostic permissions.",
    workspaceId: "developer",
  },
};

export const personaDashboardProfiles: Record<WorkspaceId, PersonaDashboardProfile> = {
  my_portal: {
    collapsedWidgetIds: ["admin-signals", "diagnostics", "audit-activity"],
    defaultVisibleWidgetIds: ["my-readiness", "upcoming-events", "current-mod-preset", "notifications"],
    description: "Simple personal view with current operation, unit tasking, resources, qualifications, attendance, and notifications.",
    emphasis: ["current operation", "my unit tasking", "my readiness", "pending personal actions"],
    id: "my_portal",
    label: "My Portal",
    primaryActionLabel: "Open Current Operation",
  },
  patrol_leader: {
    collapsedWidgetIds: ["system-health", "personnel-admin"],
    defaultVisibleWidgetIds: ["active-patrols", "awaiting-aar", "participants", "recent-patrols"],
    description: "Patrol execution view centered on active patrols and AAR follow-up.",
    emphasis: ["active patrol", "submit AAR", "manage participants"],
    id: "patrol_leader",
    label: "Patrol Leader",
    primaryActionLabel: "Start Patrol",
  },
  unit_leadership: {
    collapsedWidgetIds: ["global-admin", "discord-diagnostics"],
    defaultVisibleWidgetIds: ["unit-strength", "missing-quals", "attendance-concerns", "current-unit-tasking"],
    description: "Unit-scoped readiness, roster, qualifications, attendance, and tasking.",
    emphasis: ["unit readiness", "missing qualifications", "attendance concerns"],
    id: "unit_leadership",
    label: "Unit Leadership",
    primaryActionLabel: "Review Unit Readiness",
  },
  personnel: {
    collapsedWidgetIds: ["s3-package-details", "discord-gateway"],
    defaultVisibleWidgetIds: ["incomplete-profiles", "unlinked-users", "pending-transfers", "recent-personnel"],
    description: "Personnel administration queues and profile/roster action shortcuts.",
    emphasis: ["find member", "personnel actions", "identity repair"],
    id: "personnel",
    label: "Personnel",
    primaryActionLabel: "Find Member",
  },
  operations: {
    collapsedWidgetIds: ["personnel-deep-admin", "developer-diagnostics"],
    defaultVisibleWidgetIds: ["current-package", "readiness", "publish", "aar-queue", "recommendations"],
    description: "S3 operations, package readiness, publication, patrol AARs, and current recommendations.",
    emphasis: ["current package", "go/no-go", "publish", "review AARs"],
    id: "operations",
    label: "Operations",
    primaryActionLabel: "Open Current Package",
  },
  deployment_creator: {
    collapsedWidgetIds: ["system-admin", "personnel-global"],
    defaultVisibleWidgetIds: ["owned-deployment", "current-week", "progression", "resources", "releases"],
    description: "Deployment setup, resources, progression, releases, and next-week planning.",
    emphasis: ["current deployment", "progression", "next week"],
    id: "deployment_creator",
    label: "Deployment Creator",
    primaryActionLabel: "Open Current Week",
  },
  zeus: {
    collapsedWidgetIds: ["publishing", "personnel-admin"],
    defaultVisibleWidgetIds: ["assigned-operation", "conop", "opord", "mod-preset", "timeline"],
    description: "Execution preparation with tasking, CONOP, OPORD, mod preset, and resources.",
    emphasis: ["CONOP", "OPORD", "mod preset", "timeline"],
    id: "zeus",
    label: "Zeus",
    primaryActionLabel: "Open CONOP",
  },
  training: {
    collapsedWidgetIds: ["operations-diagnostics", "admin-settings"],
    defaultVisibleWidgetIds: ["pending-signoffs", "missing-required", "expiring-quals", "qualification-matrix"],
    description: "Qualification and training readiness work.",
    emphasis: ["award qualification", "signoffs", "requirements"],
    id: "training",
    label: "Training",
    primaryActionLabel: "Open Qualification Matrix",
  },
  command: {
    collapsedWidgetIds: ["raw-diagnostics", "builder-catalogs"],
    defaultVisibleWidgetIds: ["critical-alerts", "operational-health", "readiness", "recommendations", "failed-deliveries"],
    description: "Command-level risk, decisions, readiness, cases, and cross-domain alerts.",
    emphasis: ["what is at risk", "what needs decision", "what changed"],
    id: "command",
    label: "Command",
    primaryActionLabel: "Review Recommendations",
  },
  community: {
    collapsedWidgetIds: ["s3-planning", "qualification-matrix"],
    defaultVisibleWidgetIds: ["critical-cases", "unassigned-cases", "appeals", "moderation"],
    description: "Casework, appeals, incidents, moderation, and community workload.",
    emphasis: ["critical cases", "assign cases", "review appeals"],
    id: "community",
    label: "Community",
    primaryActionLabel: "Create Case",
  },
  administration: {
    collapsedWidgetIds: ["developer-only", "member-dashboard"],
    defaultVisibleWidgetIds: ["system-health", "identity-sync", "failed-deliveries", "permissions", "audit"],
    description: "System administration, access, Discord identity, delivery health, and audit.",
    emphasis: ["identity sync", "permissions", "failed deliveries"],
    id: "administration",
    label: "Administration",
    primaryActionLabel: "Open Discord Administration",
  },
  developer: {
    collapsedWidgetIds: ["member-facing"],
    defaultVisibleWidgetIds: ["builder", "settings", "diagnostics", "registries"],
    description: "Restricted developer diagnostics and builder foundations.",
    emphasis: ["diagnostics", "registries", "development warnings"],
    id: "developer",
    label: "Developer",
    primaryActionLabel: "Open Builder",
  },
};
