import type { DiscordApplicationTypeKey } from "@/server/discord/applications/types";

export const CURRENT_DISCORD_APPLICATION_TYPES: DiscordApplicationTypeKey[] = [
  "recruit_application",
  "rasp_application",
  "unit_transfer_request",
];

export const DISCORD_APPLICATION_CATALOG_DEFINITIONS = [
  {
    applicationTypeKey: "recruit_application",
    applicantScope: "linked_discord_user",
    availability: "available",
    communicationDomain: "recruitment",
    description: "Start the Spearhead recruit application in the Portal.",
    discordStartBehavior: "portal_continuation",
    displayName: "Recruit Application",
    eligibilitySummary: "Available from approved Community Discord entry points.",
    enabled: true,
    owningDomain: "recruitment",
    phase5ProviderKey: "recruit-provider",
    portalRoute: "/applications?type=recruit_application",
    reviewDestination: "staff-alerts",
    sortOrder: 10,
  },
  {
    applicationTypeKey: "rasp_application",
    applicantScope: "active_member",
    availability: "available",
    communicationDomain: "applications",
    description: "Apply for the 75th Ranger Regiment selection path.",
    discordStartBehavior: "portal_continuation",
    displayName: "RASP Application",
    eligibilitySummary: "Requires at least 30 days qualifying service in 3rd Infantry Division.",
    enabled: true,
    owningDomain: "rasp",
    phase5ProviderKey: "rasp-provider",
    portalRoute: "/applications?type=rasp_application",
    reviewDestination: "staff-alerts",
    sortOrder: 20,
  },
  {
    applicationTypeKey: "unit_transfer_request",
    applicantScope: "active_member",
    availability: "available",
    communicationDomain: "applications",
    description: "Request reassignment through the Portal transfer workflow.",
    discordStartBehavior: "portal_continuation",
    displayName: "Unit Transfer Request",
    eligibilitySummary: "Command is excluded; Detachment-7 remains invite-only.",
    enabled: true,
    owningDomain: "personnel",
    phase5ProviderKey: "transfer-provider",
    portalRoute: "/applications?type=unit_transfer_request",
    reviewDestination: "staff-alerts",
    sortOrder: 30,
  },
  {
    applicationTypeKey: "staff_application",
    applicantScope: "member",
    availability: "phase5_deferred",
    communicationDomain: "applications",
    description: "Future staff application entry point.",
    discordStartBehavior: "disabled",
    displayName: "Staff Application",
    eligibilitySummary: "Deferred until the Phase 5 Application Engine.",
    enabled: false,
    owningDomain: "applications",
    phase5ProviderKey: "staff-provider",
    portalRoute: "/applications",
    reviewDestination: "staff-alerts",
    sortOrder: 40,
  },
  {
    applicationTypeKey: "instructor_application",
    applicantScope: "member",
    availability: "phase5_deferred",
    communicationDomain: "training",
    description: "Future instructor application entry point.",
    discordStartBehavior: "disabled",
    displayName: "Instructor Application",
    eligibilitySummary: "Deferred until the Phase 5 Application Engine.",
    enabled: false,
    owningDomain: "training",
    phase5ProviderKey: "instructor-provider",
    portalRoute: "/applications",
    reviewDestination: "staff-alerts",
    sortOrder: 50,
  },
  {
    applicationTypeKey: "zeus_application",
    applicantScope: "member",
    availability: "phase5_deferred",
    communicationDomain: "applications",
    description: "Future Zeus application entry point.",
    discordStartBehavior: "disabled",
    displayName: "Zeus Application",
    eligibilitySummary: "Deferred until the Phase 5 Application Engine.",
    enabled: false,
    owningDomain: "operations",
    phase5ProviderKey: "zeus-provider",
    portalRoute: "/applications",
    reviewDestination: "staff-alerts",
    sortOrder: 60,
  },
  {
    applicationTypeKey: "training_request",
    applicantScope: "member",
    availability: "phase5_deferred",
    communicationDomain: "training",
    description: "Future training request entry point.",
    discordStartBehavior: "disabled",
    displayName: "Training Request",
    eligibilitySummary: "Deferred until the Phase 5 Application Engine.",
    enabled: false,
    owningDomain: "training",
    phase5ProviderKey: "training-request-provider",
    portalRoute: "/applications",
    reviewDestination: "staff-alerts",
    sortOrder: 70,
  },
  {
    applicationTypeKey: "qualification_exception",
    applicantScope: "member",
    availability: "phase5_deferred",
    communicationDomain: "training",
    description: "Future qualification exception request.",
    discordStartBehavior: "disabled",
    displayName: "Qualification Exception",
    eligibilitySummary: "Deferred until the Phase 5 Application Engine.",
    enabled: false,
    owningDomain: "training",
    phase5ProviderKey: "qualification-exception-provider",
    portalRoute: "/applications",
    reviewDestination: "staff-alerts",
    sortOrder: 80,
  },
  {
    applicationTypeKey: "community_form",
    applicantScope: "linked_user",
    availability: "phase5_deferred",
    communicationDomain: "community",
    description: "Future general community form entry point.",
    discordStartBehavior: "disabled",
    displayName: "Community Form",
    eligibilitySummary: "Deferred until the Phase 5 Application Engine.",
    enabled: false,
    owningDomain: "community",
    phase5ProviderKey: "community-form-provider",
    portalRoute: "/applications",
    reviewDestination: "staff-alerts",
    sortOrder: 90,
  },
  {
    applicationTypeKey: "custom_application",
    applicantScope: "configured",
    availability: "phase5_deferred",
    communicationDomain: "applications",
    description: "Future configurable application entry point.",
    discordStartBehavior: "disabled",
    displayName: "Custom Application",
    eligibilitySummary: "Deferred until the Phase 5 Application Engine.",
    enabled: false,
    owningDomain: "applications",
    phase5ProviderKey: "custom-application-provider",
    portalRoute: "/applications",
    reviewDestination: "staff-alerts",
    sortOrder: 100,
  },
] as const satisfies Array<{
  applicationTypeKey: DiscordApplicationTypeKey;
  applicantScope: string;
  availability: string;
  communicationDomain: string;
  description: string;
  discordStartBehavior: string;
  displayName: string;
  eligibilitySummary: string;
  enabled: boolean;
  owningDomain: string;
  phase5ProviderKey: string;
  portalRoute: string;
  reviewDestination: string;
  sortOrder: number;
}>;

export function isDiscordApplicationTypeKey(value: string): value is DiscordApplicationTypeKey {
  return DISCORD_APPLICATION_CATALOG_DEFINITIONS.some((entry) => entry.applicationTypeKey === value);
}
